<a href="https://colab.research.google.com/github/TRIAXIS-MOF/TRIAXIS-MOF/blob/main/Input_for_DFT%2C_xTB_Conformational_Energy%2C_and_Geometry_Distortion_Bound_within_the_SBU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Catatan: Pada 3 Tools (Input DFT, Energi Konformasi xTB, dan Distorsi Geometri) file terunduh di files colab harus dihapus untuk memulai setiap tools agar tidak double file yang menyebabkan file error

In [6]:
!pip install rdkit
!pip install ase
!pip install py3Dmol

import numpy as np
import pandas as pd
import matplotlib.cm as cm
import matplotlib.colors as mcolors
import py3Dmol
from ase import Atoms
from ase.io import write
from rdkit import Chem
from rdkit.Chem import AllChem, rdMolAlign
from ase.io import read
from itertools import combinations
from google.colab import files
from IPython.display import display, HTML

Requirement already satisfied: rdkit in /usr/local/lib/python3.12/dist-packages (2025.9.4)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rdkit) (2.0.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from rdkit) (11.3.0)
Requirement already satisfied: ase in /usr/local/lib/python3.12/dist-packages (3.27.0)
Requirement already satisfied: numpy>=1.21.6 in /usr/local/lib/python3.12/dist-packages (from ase) (2.0.2)
Requirement already satisfied: scipy>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from ase) (1.16.3)
Requirement already satisfied: matplotlib>=3.5.2 in /usr/local/lib/python3.12/dist-packages (from ase) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.5.2->ase) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.5.2->ase) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.5.2->ase) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.5.2->ase) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.5.2->ase) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.5.2->ase) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.5.2->ase) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.5.2->ase) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.5.2->ase) (1.17.0)
Requirement already satisfied: py3Dmol in /usr/local/lib/python3.12/dist-packages (2.5.4)

Ubah output BURAI menjadi CIF atau xyz file

In [7]:
atomic_positions_text = """
C      13.149607   6.167738   6.524006
C      12.294671   7.300114   7.001337
C      11.781530   7.399088   8.301048
H      11.969771   6.623498   9.048326
C      10.990181   8.480183   8.672863
H      10.605361   8.539886   9.690702
C      10.710142   9.502610   7.757016
C      11.996400   8.314031   6.080196
H      12.388175   8.225006   5.066640
C      11.231690   9.407699   6.458116
H      11.032786  10.212093   5.749835
C       9.955401  10.714171   8.157579
N      10.492073  11.877401   7.761677
O      13.667354   5.329358   7.473284
O      13.397165   5.970983   5.351697
C       5.638304   6.139744  10.616163
C       6.479055   7.279894  10.125507
C       6.970381   7.394460   8.818454
H       6.749850   6.644217   8.053708
C       7.741969   8.487370   8.440157
H       8.103331   8.563024   7.414806
C       8.032232   9.503523   9.359275
C       6.773876   8.298087  11.044196
H       6.386249   8.203793  12.059024
C       7.529354   9.397852  10.664374
H       7.738933  10.194598  11.378326
C       8.783348  10.714886   8.954065
N       8.245813  11.878518   9.345530
O       5.404624   5.105377   9.752187
O       5.163770   6.100031  11.733264
C      13.118758  17.617343   6.620649
C      12.271438  16.449121   6.967997
C      11.785642  16.354056   8.278763
H      12.043690  17.137970   8.991067
C      10.999025  15.275270   8.657318
H      10.634758  15.208376   9.682819
C      10.703304  14.253978   7.740940
C      11.968415  15.440027   6.045245
H      12.344510  15.510424   5.026022
C      11.205948  14.346887   6.435198
H      10.998976  13.543718   5.728028
C       9.954003  13.042108   8.151127
O      13.468235  18.482918   7.406678
O      13.486635  17.635875   5.302922
C       5.636384  17.612627  10.615570
C       6.478475  16.474076  10.125199
C       6.970804  16.361100   8.818611
H       6.752630  17.112501   8.054535
C       7.744562  15.269948   8.440532
H       8.109034  15.195415   7.416158
C       8.034661  14.253665   9.359437
C       6.774675  15.456591  11.044079
H       6.389479  15.550708  12.059579
C       7.531254  14.358073  10.664430
H       7.742280  13.561675  11.378447
C       8.783714  13.041584   8.952391
O       5.402192  18.647478   9.752300
O       5.159302  17.650500  11.731573
H       5.860291   5.252974   8.899068
H      13.463974   5.656837   8.372437
H       5.864820  18.504842   8.902191
H      14.045510  18.435541   5.189790
"""

# Parsing otomatis
symbols = []
positions = []

for line in atomic_positions_text.strip().splitlines():
    parts = line.split()
    symbols.append(parts[0])
    positions.append([float(x) for x in parts[1:4]])

# Buat object Atoms
molecule = Atoms(symbols=symbols, positions=positions)

# Cek parsing
print("Jumlah atom:", len(molecule))
print("5 atom pertama dan koordinatnya:")
for i, atom in enumerate(molecule[:5]):
    print(f"{atom.symbol} : {atom.position}")

# Simpan ke CIF atau XYZ
write("NAWXER_Linker_Free Hasil Opt.cif", molecule)
write("NAWXER_Linker_Free Hasil Opt.xyz", molecule)

print("✅ CIF dan XYZ berhasil dibuat!")

Jumlah atom: 62
5 atom pertama dan koordinatnya:
C : [13.149607  6.167738  6.524006]
C : [12.294671  7.300114  7.001337]
C : [11.78153   7.399088  8.301048]
H : [11.969771  6.623498  9.048326]
C : [10.990181  8.480183  8.672863]
✅ CIF dan XYZ berhasil dibuat!

OpenBabel dan UFF (hanya atom H saja yang mengalami relaksasi (mobile))

Upload file xyz linker embed random H cap untuk dibaca open babel

In [8]:
!apt-get install openbabel
!obabel "NAWXER_Linker_Embed_Random H Cap.xyz" -O linker.mol

mol = Chem.MolFromMolFile("linker.mol", removeHs=False)

# UFF heavy atom fixed
ff = AllChem.UFFGetMoleculeForceField(mol)
for i, atom in enumerate(mol.GetAtoms()):
    if atom.GetSymbol() != "H":
        ff.AddFixedPoint(i)

ff.Minimize(maxIts=500)

with open("NAWXER_Linker_Embed_After_UFF.xyz", "w") as f:
    f.write(Chem.MolToXYZBlock(mol))

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
openbabel is already the newest version (3.1.1+dfsg-6ubuntu5).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
1 molecule converted

Cek RMSD setelah rotasi dan translasi dihilangkan dan yang dihitung hanya perubahan jarak internal heavy atom (ini sebagai syarat/cek untuk molekul input DFT)

In [9]:
mol1 = Chem.MolFromXYZFile("NAWXER_Linker_Embed_Random H Cap.xyz")
mol2 = Chem.MolFromXYZFile("NAWXER_Linker_Embed_After_UFF.xyz")

if mol1 is None or mol2 is None:
    raise RuntimeError("GAGAL membaca XYZ. Pastikan format murni!")

# Heavy atom indices
idx = [i for i,a in enumerate(mol1.GetAtoms()) if a.GetSymbol() != "H"]

# Buat mapping 1-to-1
atom_map = [(i, i) for i in idx]

# Align dan RMSD
rmsd = rdMolAlign.AlignMol(mol2, mol1, atomMap=atom_map)

print("Heavy atom internal RMSD:", rmsd, "Å")

# Evaluasi otomatis
if rmsd < 0.02:
    print("Status: SEMPURNA → embedded benar")
elif rmsd < 0.05:
    print("Status: AMAN → bisa lanjut DFT")
elif rmsd < 0.1:
    print("Status: RAGU → cek visual")
else:
    print("Status: SALAH → struktur embedded rusak")

Heavy atom internal RMSD: 5.097603643654335e-07 Å
Status: SEMPURNA → embedded benar

Perhitungan energi konformasi linker dengan xTB

Download xTB untuk perhitungan energi konformasi linker

In [10]:
%%bash
rm -rf xtb*

wget https://github.com/grimme-lab/xtb/releases/download/v6.7.1/xtb-6.7.1-linux-x86_64.tar.xz

# extract
tar -xf xtb-6.7.1-linux-x86_64.tar.xz

# folder hasil extract
DIR=$(tar -tf xtb-6.7.1-linux-x86_64.tar.xz | head -n 1 | cut -d/ -f1)
echo "Extracted folder: $DIR"

cd "$DIR"

# set environment
export PATH=$PWD/bin:$PATH
export XTBPATH=$PWD/share/xtb

# test
bin/xtb --version

Extracted folder: xtb-dist
      -----------------------------------------------------------
     |                   =====================                   |
     |                           x T B                           |
     |                   =====================                   |
     |                         S. Grimme                         |
     |          Mulliken Center for Theoretical Chemistry        |
     |                    University of Bonn                     |
      -----------------------------------------------------------

   * xtb version 6.7.1 (edcfbbe) compiled by 'albert@albert-system' on 2024-07-22

--2026-02-11 13:49:50--  https://github.com/grimme-lab/xtb/releases/download/v6.7.1/xtb-6.7.1-linux-x86_64.tar.xz
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/211856832/0ca4f59b-4025-40a9-abba-12e99b3c8d3b?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-02-11T14%3A47%3A43Z&rscd=attachment%3B+filename%3Dxtb-6.7.1-linux-x86_64.tar.xz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-02-11T13%3A47%3A25Z&ske=2026-02-11T14%3A47%3A43Z&sks=b&skv=2018-11-09&sig=VdapAzAFHjcKTwQ88btUodA72b%2FHz80Y%2FLJNydsgEF4%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3MDgxOTU5MSwibmJmIjoxNzcwODE3NzkxLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.gJ4j8XABHHHl4cxWPkeB2I4wz0CZtkOXX7yAU8Iam10&response-content-disposition=attachment%3B%20filename%3Dxtb-6.7.1-linux-x86_64.tar.xz&response-content-type=application%2Foctet-stream [following]
--2026-02-11 13:49:51--  https://release-assets.githubusercontent.com/github-production-release-asset/211856832/0ca4f59b-4025-40a9-abba-12e99b3c8d3b?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-02-11T14%3A47%3A43Z&rscd=attachment%3B+filename%3Dxtb-6.7.1-linux-x86_64.tar.xz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-02-11T13%3A47%3A25Z&ske=2026-02-11T14%3A47%3A43Z&sks=b&skv=2018-11-09&sig=VdapAzAFHjcKTwQ88btUodA72b%2FHz80Y%2FLJNydsgEF4%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3MDgxOTU5MSwibmJmIjoxNzcwODE3NzkxLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.gJ4j8XABHHHl4cxWPkeB2I4wz0CZtkOXX7yAU8Iam10&response-content-disposition=attachment%3B%20filename%3Dxtb-6.7.1-linux-x86_64.tar.xz&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 27128568 (26M) [application/octet-stream]
Saving to: ‘xtb-6.7.1-linux-x86_64.tar.xz’

     0K .......... .......... .......... .......... ..........  0% 4.03M 6s
    50K .......... .......... .......... .......... ..........  0% 4.25M 6s
   100K .......... .......... .......... .......... ..........  0% 21.4M 5s
   150K .......... .......... .......... .......... ..........  0% 17.2M 4s
   200K .......... .......... .......... .......... ..........  0% 6.98M 4s
   250K .......... .......... .......... .......... ..........  1% 31.7M 3s
   300K .......... .......... .......... .......... ..........  1% 20.9M 3s
   350K .......... .......... .......... .......... ..........  1% 84.3M 3s
   400K .......... .......... .......... .......... ..........  1% 31.1M 2s
   450K .......... .......... .......... .......... ..........  1% 39.8M 2s
   500K .......... .......... .......... .......... ..........  2% 7.87M 2s
   550K .......... .......... .......... .......... ..........  2% 3.87M 3s
   600K .......... .......... .......... .......... ..........  2%  254M 2s
   650K .......... .......... .......... .......... ..........  2%  246M 2s
   700K .......... .......... .......... .......... ..........  2%  234M 2s
   750K .......... .......... .......... .......... ..........  3%  254M 2s
   800K .......... .......... .......... .......... ..........  3%  271M 2s
   850K .......... .......... .......... .......... ..........  3%  289M 2s
   900K .......... .......... .......... .......... ..........  3%  249M 2s
   950K .......... .......... .......... .......... ..........  3%  299M 2s
  1000K .......... .......... .......... .......... ..........  3%  315M 2s
  1050K .......... .......... .......... .......... ..........  4%  258M 1s
  1100K .......... .......... .......... .......... ..........  4%  236M 1s
  1150K .......... .......... .......... .......... ..........  4%  280M 1s
  1200K .......... .......... .......... .......... ..........  4%  265M 1s
  1250K .......... .......... .......... .......... ..........  4%  309M 1s
  1300K .......... .......... .......... .......... ..........  5% 20.9M 1s
  1350K .......... .......... .......... .......... ..........  5% 39.9M 1s
  1400K .......... .......... .......... .......... ..........  5%  231M 1s
  1450K .......... .......... .......... .......... ..........  5%  304M 1s
  1500K .......... .......... .......... .......... ..........  5% 8.80M 1s
  1550K .......... .......... .......... .......... ..........  6%  311M 1s
  1600K .......... .......... .......... .......... ..........  6% 32.1M 1s
  1650K .......... .......... .......... .......... ..........  6% 51.6M 1s
  1700K .......... .......... .......... .......... ..........  6% 22.9M 1s
  1750K .......... .......... .......... .......... ..........  6% 34.9M 1s
  1800K .......... .......... .......... .......... ..........  6% 96.2M 1s
  1850K .......... .......... .......... .......... ..........  7% 43.1M 1s
  1900K .......... .......... .......... .......... ..........  7% 10.8M 1s
  1950K .......... .......... .......... .......... ..........  7% 68.1M 1s
  2000K .......... .......... .......... .......... ..........  7% 51.3M 1s
  2050K .......... .......... .......... .......... ..........  7% 49.6M 1s
  2100K .......... .......... .......... .......... ..........  8% 27.6M 1s
  2150K .......... .......... .......... .......... ..........  8% 62.7M 1s
  2200K .......... .......... .......... .......... ..........  8% 29.3M 1s
  2250K .......... .......... .......... .......... ..........  8%  116M 1s
  2300K .......... .......... .......... .......... ..........  8% 11.4M 1s
  2350K .......... .......... .......... .......... ..........  9%  127M 1s
  2400K .......... .......... .......... .......... ..........  9% 28.3M 1s
  2450K .......... .......... .......... .......... ..........  9% 51.6M 1s
  2500K .......... .......... .......... .......... ..........  9% 28.1M 1s
  2550K .......... .......... .......... .......... ..........  9% 81.9M 1s
  2600K .......... .......... .......... .......... .......... 10% 37.6M 1s
  2650K .......... .......... .......... .......... .......... 10% 55.0M 1s
  2700K .......... .......... .......... .......... .......... 10% 39.6M 1s
  2750K .......... .......... .......... .......... .......... 10% 13.9M 1s
  2800K .......... .......... .......... .......... .......... 10% 59.1M 1s
  2850K .......... .......... .......... .......... .......... 10% 38.6M 1s
  2900K .......... .......... .......... .......... .......... 11% 66.6M 1s
  2950K .......... .......... .......... .......... .......... 11% 28.3M 1s
  3000K .......... .......... .......... .......... .......... 11% 35.2M 1s
  3050K .......... .......... .......... .......... .......... 11%  117M 1s
  3100K .......... .......... .......... .......... .......... 11% 22.7M 1s
  3150K .......... .......... .......... .......... .......... 12% 47.6M 1s
  3200K .......... .......... .......... .......... .......... 12% 19.3M 1s
  3250K .......... .......... .......... .......... .......... 12% 30.5M 1s
  3300K .......... .......... .......... .......... .......... 12%  103M 1s
  3350K .......... .......... .......... .......... .......... 12% 56.7M 1s
  3400K .......... .......... .......... .......... .......... 13% 32.7M 1s
  3450K .......... .......... .......... .......... .......... 13% 29.6M 1s
  3500K .......... .......... .......... .......... .......... 13% 23.5M 1s
  3550K .......... .......... .......... .......... .......... 13% 40.1M 1s
  3600K .......... .......... .......... .......... .......... 13% 20.7M 1s
  3650K .......... .......... .......... .......... .......... 13%  121M 1s
  3700K .......... .......... .......... .......... .......... 14% 31.6M 1s
  3750K .......... .......... .......... .......... .......... 14% 98.3M 1s
  3800K .......... .......... .......... .......... .......... 14% 23.6M 1s
  3850K .......... .......... .......... .......... .......... 14% 26.1M 1s
  3900K .......... .......... .......... .......... .......... 14% 23.5M 1s
  3950K .......... .......... .......... .......... .......... 15% 80.7M 1s
  4000K .......... .......... .......... .......... .......... 15% 63.0M 1s
  4050K .......... .......... .......... .......... .......... 15% 21.9M 1s
  4100K .......... .......... .......... .......... .......... 15% 72.2M 1s
  4150K .......... .......... .......... .......... .......... 15% 39.9M 1s
  4200K .......... .......... .......... .......... .......... 16% 21.0M 1s
  4250K .......... .......... .......... .......... .......... 16% 21.9M 1s
  4300K .......... .......... .......... .......... .......... 16%  204M 1s
  4350K .......... .......... .......... .......... .......... 16% 27.3M 1s
  4400K .......... .......... .......... .......... .......... 16% 39.3M 1s
  4450K .......... .......... .......... .......... .......... 16% 59.2M 1s
  4500K .......... .......... .......... .......... .......... 17% 26.0M 1s
  4550K .......... .......... .......... .......... .......... 17% 36.7M 1s
  4600K .......... .......... .......... .......... .......... 17% 34.4M 1s
  4650K .......... .......... .......... .......... .......... 17% 15.2M 1s
  4700K .......... .......... .......... .......... .......... 17%  131M 1s
  4750K .......... .......... .......... .......... .......... 18% 48.0M 1s
  4800K .......... .......... .......... .......... .......... 18% 26.0M 1s
  4850K .......... .......... .......... .......... .......... 18% 74.8M 1s
  4900K .......... .......... .......... .......... .......... 18% 28.7M 1s
  4950K .......... .......... .......... .......... .......... 18% 70.2M 1s
  5000K .......... .......... .......... .......... .......... 19% 46.8M 1s
  5050K .......... .......... .......... .......... .......... 19% 29.8M 1s
  5100K .......... .......... .......... .......... .......... 19% 13.8M 1s
  5150K .......... .......... .......... .......... .......... 19% 79.7M 1s
  5200K .......... .......... .......... .......... .......... 19% 34.3M 1s
  5250K .......... .......... .......... .......... .......... 20% 55.3M 1s
  5300K .......... .......... .......... .......... .......... 20% 58.0M 1s
  5350K .......... .......... .......... .......... .......... 20% 34.8M 1s
  5400K .......... .......... .......... .......... .......... 20% 56.3M 1s
  5450K .......... .......... .......... .......... .......... 20% 49.5M 1s
  5500K .......... .......... .......... .......... .......... 20% 24.2M 1s
  5550K .......... .......... .......... .......... .......... 21% 16.3M 1s
  5600K .......... .......... .......... .......... .......... 21% 97.1M 1s
  5650K .......... .......... .......... .......... .......... 21% 34.2M 1s
  5700K .......... .......... .......... .......... .......... 21% 50.8M 1s
  5750K .......... .......... .......... .......... .......... 21% 52.9M 1s
  5800K .......... .......... .......... .......... .......... 22% 35.3M 1s
  5850K .......... .......... .......... .......... .......... 22% 62.9M 1s
  5900K .......... .......... .......... .......... .......... 22% 21.0M 1s
  5950K .......... .......... .......... .......... .......... 22% 72.6M 1s
  6000K .......... .......... .......... .......... .......... 22% 16.2M 1s
  6050K .......... .......... .......... .......... .......... 23% 30.5M 1s
  6100K .......... .......... .......... .......... .......... 23%  136M 1s
  6150K .......... .......... .......... .......... .......... 23% 54.1M 1s
  6200K .......... .......... .......... .......... .......... 23% 49.4M 1s
  6250K .......... .......... .......... .......... .......... 23% 31.8M 1s
  6300K .......... .......... .......... .......... .......... 23% 31.0M 1s
  6350K .......... .......... .......... .......... .......... 24% 33.2M 1s
  6400K .......... .......... .......... .......... .......... 24%  109M 1s
  6450K .......... .......... .......... .......... .......... 24% 15.5M 1s
  6500K .......... .......... .......... .......... .......... 24% 32.1M 1s
  6550K .......... .......... .......... .......... .......... 24% 99.2M 1s
  6600K .......... .......... .......... .......... .......... 25% 46.0M 1s
  6650K .......... .......... .......... .......... .......... 25% 29.7M 1s
  6700K .......... .......... .......... .......... .......... 25% 52.1M 1s
  6750K .......... .......... .......... .......... .......... 25% 30.4M 1s
  6800K .......... .......... .......... .......... .......... 25% 42.1M 1s
  6850K .......... .......... .......... .......... .......... 26% 55.4M 1s
  6900K .......... .......... .......... .......... .......... 26% 14.8M 1s
  6950K .......... .......... .......... .......... .......... 26% 49.1M 1s
  7000K .......... .......... .......... .......... .......... 26%  108M 1s
  7050K .......... .......... .......... .......... .......... 26% 48.9M 1s
  7100K .......... .......... .......... .......... .......... 26% 20.0M 1s
  7150K .......... .......... .......... .......... .......... 27% 49.4M 1s
  7200K .......... .......... .......... .......... .......... 27% 43.8M 1s
  7250K .......... .......... .......... .......... .......... 27% 37.4M 1s
  7300K .......... .......... .......... .......... .......... 27% 50.8M 1s
  7350K .......... .......... .......... .......... .......... 27% 18.6M 1s
  7400K .......... .......... .......... .......... .......... 28% 38.1M 1s
  7450K .......... .......... .......... .......... .......... 28% 93.6M 1s
  7500K .......... .......... .......... .......... .......... 28% 17.1M 1s
  7550K .......... .......... .......... .......... .......... 28%  104M 1s
  7600K .......... .......... .......... .......... .......... 28% 52.9M 1s
  7650K .......... .......... .......... .......... .......... 29% 24.1M 1s
  7700K .......... .......... .......... .......... .......... 29% 31.7M 1s
  7750K .......... .......... .......... .......... .......... 29%  124M 1s
  7800K .......... .......... .......... .......... .......... 29% 24.7M 1s
  7850K .......... .......... .......... .......... .......... 29% 35.8M 1s
  7900K .......... .......... .......... .......... .......... 30% 33.9M 1s
  7950K .......... .......... .......... .......... .......... 30% 21.6M 1s
  8000K .......... .......... .......... .......... .......... 30% 90.9M 1s
  8050K .......... .......... .......... .......... .......... 30% 74.5M 1s
  8100K .......... .......... .......... .......... .......... 30% 25.2M 1s
  8150K .......... .......... .......... .......... .......... 30% 33.1M 1s
  8200K .......... .......... .......... .......... .......... 31% 88.6M 1s
  8250K .......... .......... .......... .......... .......... 31% 20.3M 1s
  8300K .......... .......... .......... .......... .......... 31% 38.5M 1s
  8350K .......... .......... .......... .......... .......... 31% 47.4M 1s
  8400K .......... .......... .......... .......... .......... 31% 22.8M 1s
  8450K .......... .......... .......... .......... .......... 32% 77.4M 1s
  8500K .......... .......... .......... .......... .......... 32% 56.2M 1s
  8550K .......... .......... .......... .......... .......... 32% 28.4M 1s
  8600K .......... .......... .......... .......... .......... 32% 32.8M 1s
  8650K .......... .......... .......... .......... .......... 32% 76.8M 1s
  8700K .......... .......... .......... .......... .......... 33% 17.3M 1s
  8750K .......... .......... .......... .......... .......... 33% 54.6M 1s
  8800K .......... .......... .......... .......... .......... 33% 59.4M 1s
  8850K .......... .......... .......... .......... .......... 33% 18.1M 1s
  8900K .......... .......... .......... .......... .......... 33% 56.8M 1s
  8950K .......... .......... .......... .......... .......... 33% 66.9M 1s
  9000K .......... .......... .......... .......... .......... 34% 37.4M 1s
  9050K .......... .......... .......... .......... .......... 34% 39.8M 1s
  9100K .......... .......... .......... .......... .......... 34% 24.6M 1s
  9150K .......... .......... .......... .......... .......... 34% 33.5M 1s
  9200K .......... .......... .......... .......... .......... 34% 44.3M 1s
  9250K .......... .......... .......... .......... .......... 35% 64.3M 1s
  9300K .......... .......... .......... .......... .......... 35% 19.3M 1s
  9350K .......... .......... .......... .......... .......... 35% 41.8M 1s
  9400K .......... .......... .......... .......... .......... 35%  111M 1s
  9450K .......... .......... .......... .......... .......... 35% 49.1M 1s
  9500K .......... .......... .......... .......... .......... 36% 28.8M 1s
  9550K .......... .......... .......... .......... .......... 36% 24.8M 1s
  9600K .......... .......... .......... .......... .......... 36% 36.0M 1s
  9650K .......... .......... .......... .......... .......... 36% 46.1M 1s
  9700K .......... .......... .......... .......... .......... 36% 62.3M 1s
  9750K .......... .......... .......... .......... .......... 36% 19.1M 1s
  9800K .......... .......... .......... .......... .......... 37% 45.4M 1s
  9850K .......... .......... .......... .......... .......... 37% 56.2M 1s
  9900K .......... .......... .......... .......... .......... 37% 21.5M 1s
  9950K .......... .......... .......... .......... .......... 37%  107M 1s
 10000K .......... .......... .......... .......... .......... 37% 28.3M 1s
 10050K .......... .......... .......... .......... .......... 38% 40.6M 1s
 10100K .......... .......... .......... .......... .......... 38% 42.5M 1s
 10150K .......... .......... .......... .......... .......... 38% 52.7M 0s
 10200K .......... .......... .......... .......... .......... 38% 20.3M 0s
 10250K .......... .......... .......... .......... .......... 38% 42.8M 0s
 10300K .......... .......... .......... .......... .......... 39% 32.9M 0s
 10350K .......... .......... .......... .......... .......... 39% 29.1M 0s
 10400K .......... .......... .......... .......... .......... 39% 25.9M 0s
 10450K .......... .......... .......... .......... .......... 39% 53.9M 0s
 10500K .......... .......... .......... .......... .......... 39% 88.2M 0s
 10550K .......... .......... .......... .......... .......... 40% 36.6M 0s
 10600K .......... .......... .......... .......... .......... 40% 52.5M 0s
 10650K .......... .......... .......... .......... .......... 40% 21.1M 0s
 10700K .......... .......... .......... .......... .......... 40% 48.0M 0s
 10750K .......... .......... .......... .......... .......... 40% 35.2M 0s
 10800K .......... .......... .......... .......... .......... 40% 27.8M 0s
 10850K .......... .......... .......... .......... .......... 41%  105M 0s
 10900K .......... .......... .......... .......... .......... 41% 32.9M 0s
 10950K .......... .......... .......... .......... .......... 41% 40.3M 0s
 11000K .......... .......... .......... .......... .......... 41% 29.9M 0s
 11050K .......... .......... .......... .......... .......... 41% 61.3M 0s
 11100K .......... .......... .......... .......... .......... 42% 16.1M 0s
 11150K .......... .......... .......... .......... .......... 42% 89.4M 0s
 11200K .......... .......... .......... .......... .......... 42% 45.0M 0s
 11250K .......... .......... .......... .......... .......... 42% 26.8M 0s
 11300K .......... .......... .......... .......... .......... 42%  108M 0s
 11350K .......... .......... .......... .......... .......... 43% 29.3M 0s

Menambahkan xTB ke path

In [11]:
import os

os.environ["PATH"] += ":" + "/content/xtb-dist/bin"
os.environ["XTBPATH"] = "/content/xtb-dist/share/xtb"

Upload file linker embedd after UFF

In [12]:
from google.colab import files
files.upload()

Saving FATQID_Linker_Embed_After_UFF.xyz to FATQID_Linker_Embed_After_UFF.xyz

{'FATQID_Linker_Embed_After_UFF.xyz': b'37\nProperties=species:S:1:pos:R:3 pbc="F F F"\nC      8.773400    9.153000   17.322200\nC      9.516900    9.793900   16.205700\nC      9.104500   11.014600   15.701100\nH      8.233944   11.514115   16.108198\nC      9.773000   11.623700   14.652200\nH      9.386110   12.555952   14.261339\nC     11.306700    9.821400   14.595800\nH     12.190288    9.324225   14.216290\nC     10.616400    9.224800   15.667200\nH     10.992618    8.280965   16.042180\nC     10.894400   10.995900   14.082700\nC     11.709600   13.023100   12.876000\nH     11.296438   13.640089   13.662287\nC     11.597200   11.632800   12.946500\nC     12.206300   10.880300   11.937200\nH     12.162482    9.800632   11.977260\nC     12.893500   11.517500   10.888300\nC     12.918500   12.905700   10.913700\nH     13.406921   13.443164   10.112175\nC     13.596300   10.758800    9.839500\nC     13.096500    9.574700    9.419400\nH     12.164174    9.189073    9.811203\nC     13.730600    8.825000    8.393200\nH     13.291064    7.887589    8.075559\nC     14.917600    9.306000    7.840600\nC     15.386100   10.493000    8.283200\nH     16.264543   10.963278    7.867334\nC     14.739500   11.202100    9.284100\nH     15.190853   12.129248    9.614437\nC     15.629700    8.525100    6.822800\nO     16.727700    8.990500    6.417900\nO     15.098100    7.457200    6.424900\nN     12.357100   13.644100   11.888100\nO      7.738900    9.704600   17.749300\nO      9.242900    8.062500   17.735800\nH      8.793255    7.550080   18.485613\nH     17.418551    9.430086    7.013418\n'}

Perhitungan energi linker embedd dengan xTB

In [13]:
%%bash
xtb FATQID_Linker_Embed_After_UFF.xyz --gfn2 | tee xtb.out

      -----------------------------------------------------------
     |                   =====================                   |
     |                           x T B                           |
     |                   =====================                   |
     |                         S. Grimme                         |
     |          Mulliken Center for Theoretical Chemistry        |
     |                    University of Bonn                     |
      -----------------------------------------------------------

   * xtb version 6.7.1 (edcfbbe) compiled by 'albert@albert-system' on 2024-07-22

   xtb is free software: you can redistribute it and/or modify it under
   the terms of the GNU Lesser General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   xtb is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU Lesser General Public License for more details.

   Cite this work as:
   * C. Bannwarth, E. Caldeweyher, S. Ehlert, A. Hansen, P. Pracht,
     J. Seibert, S. Spicher, S. Grimme, WIREs Comput. Mol. Sci., 2020, 11,
     e01493. DOI: 10.1002/wcms.1493

   for GFN2-xTB:
   * C. Bannwarth, S. Ehlert and S. Grimme., J. Chem. Theory Comput., 2019,
     15, 1652-1671. DOI: 10.1021/acs.jctc.8b01176
   for GFN1-xTB:
   * S. Grimme, C. Bannwarth, P. Shushkov, J. Chem. Theory Comput., 2017,
     13, 1989-2009. DOI: 10.1021/acs.jctc.7b00118
   for GFN0-xTB:
   * P. Pracht, E. Caldeweyher, S. Ehlert, S. Grimme, ChemRxiv, 2019, preprint.
     DOI: 10.26434/chemrxiv.8326202.v1
   for GFN-FF:
   * S. Spicher and S. Grimme, Angew. Chem. Int. Ed., 2020, 59, 15665-15673.
     DOI: 10.1002/anie.202004239

   for ALPB and GBSA implicit solvation:
   * S. Ehlert, M. Stahn, S. Spicher, S. Grimme, J. Chem. Theory Comput.,
     2021, 17, 4250-4261. DOI: 10.1021/acs.jctc.1c00471

   for ddCOSMO and CPCM-X implicit solvation:
   * M. Stahn, S. Ehlert, S. Grimme, J. Phys. Chem. A,
     2023, XX, XXXX-XXXX. DOI: 10.1021/acs.jpca.3c04382

   for DFT-D4:
   * E. Caldeweyher, C. Bannwarth and S. Grimme, J. Chem. Phys., 2017,
     147, 034112. DOI: 10.1063/1.4993215
   * E. Caldeweyher, S. Ehlert, A. Hansen, H. Neugebauer, S. Spicher,
     C. Bannwarth and S. Grimme, J. Chem. Phys., 2019, 150, 154122.
     DOI: 10.1063/1.5090222
   * E. Caldeweyher, J.-M. Mewes, S. Ehlert and S. Grimme, Phys. Chem. Chem. Phys.
     2020, 22, 8499-8512. DOI: 10.1039/D0CP00502A

   for sTDA-xTB:
   * S. Grimme and C. Bannwarth, J. Chem. Phys., 2016, 145, 054103.
     DOI: 10.1063/1.4959605

   in the mass-spec context:
   * V. Asgeirsson, C. Bauer and S. Grimme, Chem. Sci., 2017, 8, 4879.
     DOI: 10.1039/c7sc00601b
   * J. Koopman and S. Grimme, ACS Omega 2019, 4, 12, 15120-15133.
     DOI: 10.1021/acsomega.9b02011

   for metadynamics refer to:
   * S. Grimme, J. Chem. Theory Comput., 2019, 155, 2847-2862
     DOI: 10.1021/acs.jctc.9b00143

   for SPH calculations refer to:
   * S. Spicher and S. Grimme, J. Chem. Theory Comput., 2021, 17, 1701-1714
     DOI: 10.1021/acs.jctc.0c01306

   for ONIOM refer to:
   * C. Plett, A. Katbashev, S. Ehlert, S. Grimme, M. Bursch,
     Phys. Chem. Chem. Phys., 2023, 25, 17860-17868. DOI: 10.1039/D3CP02178E

   for DIPRO refer to:
   * J. Kohn, N. Gildemeister, S. Grimme, D. Fazzi, A. Hansen,
     J. Chem. Phys., 2023, just accepted.

   for PTB refer to:
   * S. Grimme, M. Mueller, A. Hansen, J. Chem. Phys., 2023, 158, 124111.
     DOI: 10.1063/5.0137838

   with help from (in alphabetical order)
   P. Atkinson, C. Bannwarth, F. Bohle, G. Brandenburg, E. Caldeweyher
   M. Checinski, S. Dohm, S. Ehlert, S. Ehrlich, I. Gerasimov, C. Hölzer
   A. Katbashev, J. Kohn, J. Koopman, C. Lavigne, S. Lehtola, F. März, M. Müller,
   F. Musil, H. Neugebauer, J. Pisarek, C. Plett, P. Pracht, F. Pultar,
   J. Seibert, P. Shushkov, S. Spicher, M. Stahn, M. Steiner, T. Strunk,
   J. Stückrath, T. Rose, and J. Unsleber

 * started run on 2026/02/11 at 13:50:23.837
   ID    Z sym.   atoms
    1    6 C      1-3, 5, 7, 9, 11, 12, 14, 15, 17, 18, 20, 21, 23, 25, 26,
                  28, 30
    2    1 H      4, 6, 8, 10, 13, 16, 19, 22, 24, 27, 29, 36, 37
    3    8 O      31, 32, 34, 35
    4    7 N      33

           -------------------------------------------------
          |                Calculation Setup                |
           -------------------------------------------------

          program call               : xtb FATQID_Linker_Embed_After_UFF.xyz --gfn2
          hostname                   : 13770b92efc8
          coordinate file            : FATQID_Linker_Embed_After_UFF.xyz
          omp threads                :                     2


           -------------------------------------------------
          |                 G F N 2 - x T B                 |
           -------------------------------------------------

        Reference                      10.1021/acs.jctc.8b01176
      * Hamiltonian:
        H0-scaling (s, p, d)           1.850000    2.230000    2.230000
        zeta-weighting                 0.500000
      * Dispersion:
        s8                             2.700000
        a1                             0.520000
        a2                             5.000000
        s9                             5.000000
      * Repulsion:
        kExp                           1.500000    1.000000
        rExp                           1.000000
      * Coulomb:
        alpha                          2.000000
        third order                    shell-resolved
        anisotropic                    true
        a3                             3.000000
        a5                             4.000000
        cn-shift                       1.200000
        cn-exp                         4.000000
        max-rad                        5.000000


          ...................................................
          :                      SETUP                      :
          :.................................................:
          :  # basis functions                 109          :
          :  # atomic orbitals                 109          :
          :  # shells                           61          :
          :  # electrons                       118          :
          :  max. iterations                   250          :
          :  Hamiltonian                  GFN2-xTB          :
          :  restarted?                      false          :
          :  GBSA solvation                  false          :
          :  PC potential                    false          :
          :  electronic temp.          300.0000000     K    :
          :  accuracy                    1.0000000          :
          :  -> integral cutoff          0.2500000E+02      :
          :  -> integral neglect         0.1000000E-07      :
          :  -> SCF convergence          0.1000000E-05 Eh   :
          :  -> wf. convergence          0.1000000E-03 e    :
          :  Broyden damping             0.4000000          :
          :  net charge                          0          :
          :  unpaired electrons                  0          :
          ...................................................

 iter      E             dE          RMSdq      gap      omega  full diag
   1    -67.3733506 -0.673734E+02  0.456E+00    2.62       0.0  T
   2    -67.4613516 -0.880010E-01  0.260E+00    2.69       1.0  T
   3    -67.4616987 -0.347087E-03  0.128E+00    2.58       1.0  T
   4    -67.4723342 -0.106354E-01  0.236E-01    2.43       1.0  T
   5    -67.4737553 -0.142114E-02  0.960E-02    2.44       1.0  T
   6    -67.4739500 -0.194727E-03  0.412E-02    2.42       1.0  T
   7    -67.4739643 -0.142838E-04  0.182E-02    2.42       1.0  T
   8    -67.4739712 -0.689452E-05  0.708E-03    2.43       2.3  T
   9    -67.4739715 -0.351547E-06  0.334E-03    2.43       4.9  T
  10    -67.4739718 -0.228514E-06  0.137E-03    2.43      12.0  T
  11    -67.4739718 -0.119750E-07  0.524E-04    2.43      31.4  T
  12    -67.4739718 -0.468719E-08  0.266E-04    2.43      61.9  T

   *** convergence criteria satisfied after 12 iterations ***

         #    Occupation            Energy/Eh            Energy/eV
      -------------------------------------------------------------
         1        2.0000           -0.7637801             -20.7835
       ...           ...                  ...                  ...
        53        2.0000           -0.4268970             -11.6165
        54        2.0000           -0.4227905             -11.5047
        55        2.0000           -0.4226001             -11.4995
        56        2.0000           -0.4117727             -11.2049
        57        2.0000           -0.4111611             -11.1883
        58        2.0000           -0.4073280             -11.0840
        59        2.0000           -0.3792316             -10.3194 (HOMO)
        60                         -0.2899550              -7.8901 (LUMO)
        61                         -0.2837085              -7.7201
        62                         -0.2613226              -7.1109
        63                         -0.2534660              -6.8972
        64                         -0.2471624              -6.7256
       ...                                ...                  ...
       109                          0.7219508              19.6453
      -------------------------------------------------------------
                  HL-Gap            0.0892766 Eh            2.4293 eV
             Fermi-level           -0.3345933 Eh           -9.1047 eV

 SCC (total)                   0 d,  0 h,  0 min,  0.076 sec
 SCC setup                      ...        0 min,  0.001 sec (  0.976%)
 Dispersion                     ...        0 min,  0.001 sec (  1.210%)
 classical contributions        ...        0 min,  0.000 sec (  0.124%)
 integral evaluation            ...        0 min,  0.009 sec ( 12.175%)
 iterations                     ...        0 min,  0.038 sec ( 50.371%)
 molecular gradient             ...        0 min,  0.026 sec ( 33.911%)
 printout                       ...        0 min,  0.001 sec (  1.147%)

         :::::::::::::::::::::::::::::::::::::::::::::::::::::
         ::                     SUMMARY                     ::
         :::::::::::::::::::::::::::::::::::::::::::::::::::::
         :: total energy             -66.457313707197 Eh    ::
         :: gradient norm              0.264143196859 Eh/a0 ::
         :: HOMO-LUMO gap              2.429341223173 eV    ::
         ::.................................................::
         :: SCC energy               -67.474411997690 Eh    ::
         :: -> isotropic ES            0.113224537699 Eh    ::
         :: -> anisotropic ES          0.004610638609 Eh    ::
         :: -> anisotropic XC          0.025302946350 Eh    ::
         :: -> dispersion             -0.041348755905 Eh    ::
         :: repulsion energy           1.017098290493 Eh    ::
         :: add. restraining           0.000000000000 Eh    ::
         :: total charge               0.000000000000 e     ::
         :::::::::::::::::::::::::::::::::::::::::::::::::::::

           -------------------------------------------------
          |                Property Printout                |
           -------------------------------------------------

    * Orbital Energies and Occupations

         #    Occupation            Energy/Eh            Energy/eV
      -------------------------------------------------------------
         1        2.0000           -0.7637801             -20.7835
       ...           ...                  ...                  ...
        47        2.0000           -0.4599176             -12.5150
        48        2.0000           -0.4545742             -12.3696
        49        2.0000           -0.4508183             -12.2674
        50        2.0000           -0.4475036             -12.1772
        51        2.0000           -0.4438383             -12.0775
        52        2.0000           -0.4366929             -11.8830
        53        2.0000           -0.4268970             -11.6165
        54        2.0000           -0.4227905             -11.5047
        55        2.0000           -0.4226001             -11.4995
        56        2.0000           -0.4117727             -11.2049
        57        2.0000           -0.4111611             -11.1883
        58        2.0000           -0.4073280             -11.0840
        59        2.0000           -0.3792316             -10.3194 (HOMO)
        60                         -0.2899550              -7.8901 (LUMO)
        61                         -0.2837085              -7.7201
        62                         -0.2613226              -7.1109
        63                         -0.2534660              -6.8972
        64                         -0.2471624              -6.7256
        65                         -0.2441681              -6.6442
        66                         -0.1980712              -5.3898
        67                         -0.1788654              -4.8672
        68                         -0.1269707              -3.4550
        69                         -0.0908649              -2.4726
        70                         -0.0805378              -2.1915
       ...                                ...                  ...
       109                          0.7219508              19.6453
      -------------------------------------------------------------
                  HL-Gap            0.0892766 Eh            2.4293 eV
             Fermi-level           -0.3345933 Eh           -9.1047 eV

     #   Z          covCN         q      C6AA      α(0)
     1   6 C        2.698     0.360    20.893     7.481
     2   6 C        2.971    -0.010    28.262     8.720
     3   6 C        2.938    -0.019    28.472     8.751
     4   1 H        0.925     0.066     2.128     2.281
     5   6 C        2.929    -0.035    28.861     8.810
     6   1 H        0.925     0.046     2.368     2.406
     7   6 C        2.933    -0.032    28.803     8.802
     8   1 H        0.925     0.039     2.457     2.451
     9   6 C        2.944    -0.025    28.626     8.775
    10   1 H        0.925     0.049     2.329     2.387
    11   6 C        2.978     0.019    27.587     8.616
    12   6 C        2.889     0.054    26.782     8.485
    13   1 H        0.925     0.048     2.345     2.394
    14   6 C        2.966     0.000    28.024     8.683
    15   6 C        2.932    -0.023    28.571     8.766
    16   1 H        0.925     0.041     2.433     2.439
    17   6 C        2.970    -0.002    28.061     8.689
    18   6 C        2.892     0.051    26.852     8.496
    19   1 H        0.925     0.044     2.391     2.418
    20   6 C        2.979     0.024    27.460     8.596
    21   6 C        2.953    -0.032    28.794     8.801
    22   1 H        0.925     0.043     2.404     2.425
    23   6 C        2.934    -0.021    28.543     8.762
    24   1 H        0.925     0.070     2.087     2.259
    25   6 C        2.974    -0.029    28.721     8.791
    26   6 C        2.943    -0.031    28.781     8.799
    27   1 H        0.926     0.031     2.568     2.506
    28   6 C        2.958    -0.033    28.821     8.805
    29   1 H        0.925     0.038     2.480     2.463
    30   6 C        2.701     0.361    20.872     7.478
    31   8 O        1.654    -0.343    19.778     6.003
    32   8 O        0.857    -0.419    22.056     6.297
    33   7 N        1.832    -0.217    26.571     7.639
    34   8 O        0.857    -0.462    22.955     6.424
    35   8 O        1.653    -0.330    19.541     5.967
    36   1 H        0.796     0.337     0.621     1.239
    37   1 H        0.796     0.339     0.617     1.234

 Mol. C6AA /au·bohr⁶  :      19931.562869
 Mol. C8AA /au·bohr⁸  :     496467.620108
 Mol. α(0) /au        :        224.338023


Wiberg/Mayer (AO) data.
largest (>0.10) Wiberg bond orders for each atom

 ---------------------------------------------------------------------------
     #   Z sym  total        # sym  WBO       # sym  WBO       # sym  WBO
 ---------------------------------------------------------------------------
     1   6 C    3.914 --    34 O    1.662    35 O    1.216     2 C    0.987
     2   6 C    3.985 --     9 C    1.446     3 C    1.349     1 C    0.987
     3   6 C    3.987 --     5 C    1.501     2 C    1.349     4 H    0.965
                             7 C    0.105
     4   1 H    0.995 --     3 C    0.965
     5   6 C    3.989 --     3 C    1.501    11 C    1.333     6 H    0.968
                             9 C    0.113
     6   1 H    0.997 --     5 C    0.968
     7   6 C    3.992 --    11 C    1.453     9 C    1.388     8 H    0.966
                             3 C    0.105
     8   1 H    0.998 --     7 C    0.966
     9   6 C    3.990 --     2 C    1.446     7 C    1.388    10 H    0.967
                             5 C    0.113
    10   1 H    0.997 --     9 C    0.967
    11   6 C    3.989 --     7 C    1.453     5 C    1.333    14 C    1.041
    12   6 C    3.973 --    33 N    1.454    14 C    1.364    13 H    0.960
    13   1 H    0.997 --    12 C    0.960
    14   6 C    3.987 --    15 C    1.409    12 C    1.364    11 C    1.041
                            18 C    0.100
    15   6 C    3.986 --    14 C    1.409    17 C    1.384    16 H    0.963
                            33 N    0.101
    16   1 H    0.998 --    15 C    0.963
    17   6 C    3.987 --    18 C    1.391    15 C    1.384    20 C    1.038
    18   6 C    3.973 --    33 N    1.425    17 C    1.391    19 H    0.961
                            14 C    0.100
    19   1 H    0.997 --    18 C    0.961
    20   6 C    3.991 --    28 C    1.399    21 C    1.399    17 C    1.038
    21   6 C    3.991 --    23 C    1.443    20 C    1.399    22 H    0.967
                            26 C    0.107
    22   1 H    0.998 --    21 C    0.967
    23   6 C    3.984 --    21 C    1.443    25 C    1.375    24 H    0.967
                            28 C    0.119
    24   1 H    0.995 --    23 C    0.967
    25   6 C    3.986 --    26 C    1.415    23 C    1.375    30 C    1.005
    26   6 C    3.993 --    28 C    1.429    25 C    1.415    27 H    0.962
                            21 C    0.107
    27   1 H    0.999 --    26 C    0.962
    28   6 C    3.993 --    26 C    1.429    20 C    1.399    29 H    0.966
                            23 C    0.119
    29   1 H    0.998 --    28 C    0.966
    30   6 C    3.918 --    32 O    1.679    31 O    1.184    25 C    1.005
    31   8 O    2.229 --    30 C    1.184    37 H    0.836    32 O    0.148
    32   8 O    1.984 --    30 C    1.679    31 O    0.148
    33   7 N    3.062 --    12 C    1.454    18 C    1.425    15 C    0.101
    34   8 O    1.957 --     1 C    1.662    35 O    0.179
    35   8 O    2.273 --     1 C    1.216    36 H    0.844    34 O    0.179
    36   1 H    0.885 --    35 O    0.844
    37   1 H    0.885 --    31 O    0.836
 ---------------------------------------------------------------------------

Topologies differ in total number of bonds
Writing topology from bond orders to xtbtopo.mol

molecular dipole:
                 x           y           z       tot (Debye)
 q only:        1.253       0.333       0.807
   full:        1.396       0.044       1.099       4.518
molecular quadrupole (traceless):
                xx          xy          yy          xz          yz          zz
 q only:       45.320      61.974     -29.218      83.707       1.285     -16.102
  q+dip:       54.463      59.909     -53.956      93.518      -7.749      -0.507
   full:       55.710      59.963     -56.489      98.410      -7.972       0.779


           -------------------------------------------------
          | TOTAL ENERGY              -66.457313707197 Eh   |

normal termination of xtb

Perhitungan energi free (linker embedd setelah optimasi geometri) dengan xTB

In [14]:
!xtb FATQID_Linker_Embed_After_UFF.xyz --opt --gfn2 | tee xtb_opt.out

      -----------------------------------------------------------
     |                   =====================                   |
     |                           x T B                           |
     |                   =====================                   |
     |                         S. Grimme                         |
     |          Mulliken Center for Theoretical Chemistry        |
     |                    University of Bonn                     |
      -----------------------------------------------------------

   * xtb version 6.7.1 (edcfbbe) compiled by 'albert@albert-system' on 2024-07-22

   xtb is free software: you can redistribute it and/or modify it under
   the terms of the GNU Lesser General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   xtb is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU Lesser General Public License for more details.

   Cite this work as:
   * C. Bannwarth, E. Caldeweyher, S. Ehlert, A. Hansen, P. Pracht,
     J. Seibert, S. Spicher, S. Grimme, WIREs Comput. Mol. Sci., 2020, 11,
     e01493. DOI: 10.1002/wcms.1493

   for GFN2-xTB:
   * C. Bannwarth, S. Ehlert and S. Grimme., J. Chem. Theory Comput., 2019,
     15, 1652-1671. DOI: 10.1021/acs.jctc.8b01176
   for GFN1-xTB:
   * S. Grimme, C. Bannwarth, P. Shushkov, J. Chem. Theory Comput., 2017,
     13, 1989-2009. DOI: 10.1021/acs.jctc.7b00118
   for GFN0-xTB:
   * P. Pracht, E. Caldeweyher, S. Ehlert, S. Grimme, ChemRxiv, 2019, preprint.
     DOI: 10.26434/chemrxiv.8326202.v1
   for GFN-FF:
   * S. Spicher and S. Grimme, Angew. Chem. Int. Ed., 2020, 59, 15665-15673.
     DOI: 10.1002/anie.202004239

   for ALPB and GBSA implicit solvation:
   * S. Ehlert, M. Stahn, S. Spicher, S. Grimme, J. Chem. Theory Comput.,
     2021, 17, 4250-4261. DOI: 10.1021/acs.jctc.1c00471

   for ddCOSMO and CPCM-X implicit solvation:
   * M. Stahn, S. Ehlert, S. Grimme, J. Phys. Chem. A,
     2023, XX, XXXX-XXXX. DOI: 10.1021/acs.jpca.3c04382

   for DFT-D4:
   * E. Caldeweyher, C. Bannwarth and S. Grimme, J. Chem. Phys., 2017,
     147, 034112. DOI: 10.1063/1.4993215
   * E. Caldeweyher, S. Ehlert, A. Hansen, H. Neugebauer, S. Spicher,
     C. Bannwarth and S. Grimme, J. Chem. Phys., 2019, 150, 154122.
     DOI: 10.1063/1.5090222
   * E. Caldeweyher, J.-M. Mewes, S. Ehlert and S. Grimme, Phys. Chem. Chem. Phys.
     2020, 22, 8499-8512. DOI: 10.1039/D0CP00502A

   for sTDA-xTB:
   * S. Grimme and C. Bannwarth, J. Chem. Phys., 2016, 145, 054103.
     DOI: 10.1063/1.4959605

   in the mass-spec context:
   * V. Asgeirsson, C. Bauer and S. Grimme, Chem. Sci., 2017, 8, 4879.
     DOI: 10.1039/c7sc00601b
   * J. Koopman and S. Grimme, ACS Omega 2019, 4, 12, 15120-15133.
     DOI: 10.1021/acsomega.9b02011

   for metadynamics refer to:
   * S. Grimme, J. Chem. Theory Comput., 2019, 155, 2847-2862
     DOI: 10.1021/acs.jctc.9b00143

   for SPH calculations refer to:
   * S. Spicher and S. Grimme, J. Chem. Theory Comput., 2021, 17, 1701-1714
     DOI: 10.1021/acs.jctc.0c01306

   for ONIOM refer to:
   * C. Plett, A. Katbashev, S. Ehlert, S. Grimme, M. Bursch,
     Phys. Chem. Chem. Phys., 2023, 25, 17860-17868. DOI: 10.1039/D3CP02178E

   for DIPRO refer to:
   * J. Kohn, N. Gildemeister, S. Grimme, D. Fazzi, A. Hansen,
     J. Chem. Phys., 2023, just accepted.

   for PTB refer to:
   * S. Grimme, M. Mueller, A. Hansen, J. Chem. Phys., 2023, 158, 124111.
     DOI: 10.1063/5.0137838

   with help from (in alphabetical order)
   P. Atkinson, C. Bannwarth, F. Bohle, G. Brandenburg, E. Caldeweyher
   M. Checinski, S. Dohm, S. Ehlert, S. Ehrlich, I. Gerasimov, C. Hölzer
   A. Katbashev, J. Kohn, J. Koopman, C. Lavigne, S. Lehtola, F. März, M. Müller,
   F. Musil, H. Neugebauer, J. Pisarek, C. Plett, P. Pracht, F. Pultar,
   J. Seibert, P. Shushkov, S. Spicher, M. Stahn, M. Steiner, T. Strunk,
   J. Stückrath, T. Rose, and J. Unsleber

 * started run on 2026/02/11 at 13:50:28.214
   ID    Z sym.   atoms
    1    6 C      1-3, 5, 7, 9, 11, 12, 14, 15, 17, 18, 20, 21, 23, 25, 26,
                  28, 30
    2    1 H      4, 6, 8, 10, 13, 16, 19, 22, 24, 27, 29, 36, 37
    3    8 O      31, 32, 34, 35
    4    7 N      33

           -------------------------------------------------
          |                Calculation Setup                |
           -------------------------------------------------

          program call               : xtb FATQID_Linker_Embed_After_UFF.xyz --opt --gfn2
          hostname                   : 13770b92efc8
          coordinate file            : FATQID_Linker_Embed_After_UFF.xyz
          omp threads                :                     2


           -------------------------------------------------
          |                 G F N 2 - x T B                 |
           -------------------------------------------------

        Reference                      10.1021/acs.jctc.8b01176
      * Hamiltonian:
        H0-scaling (s, p, d)           1.850000    2.230000    2.230000
        zeta-weighting                 0.500000
      * Dispersion:
        s8                             2.700000
        a1                             0.520000
        a2                             5.000000
        s9                             5.000000
      * Repulsion:
        kExp                           1.500000    1.000000
        rExp                           1.000000
      * Coulomb:
        alpha                          2.000000
        third order                    shell-resolved
        anisotropic                    true
        a3                             3.000000
        a5                             4.000000
        cn-shift                       1.200000
        cn-exp                         4.000000
        max-rad                        5.000000

q/qsh data taken from xtbrestart
CAMM data taken from xtbrestart

          ...................................................
          :                      SETUP                      :
          :.................................................:
          :  # basis functions                 109          :
          :  # atomic orbitals                 109          :
          :  # shells                           61          :
          :  # electrons                       118          :
          :  max. iterations                   250          :
          :  Hamiltonian                  GFN2-xTB          :
          :  restarted?                       true          :
          :  GBSA solvation                  false          :
          :  PC potential                    false          :
          :  electronic temp.          300.0000000     K    :
          :  accuracy                    1.0000000          :
          :  -> integral cutoff          0.2500000E+02      :
          :  -> integral neglect         0.1000000E-07      :
          :  -> SCF convergence          0.1000000E-05 Eh   :
          :  -> wf. convergence          0.1000000E-03 e    :
          :  Broyden damping             0.4000000          :
          :  net charge                          0          :
          :  unpaired electrons                  0          :
          ...................................................

 iter      E             dE          RMSdq      gap      omega  full diag
   1    -67.4739718 -0.674740E+02  0.142E-04    2.43       0.0  T
   2    -67.4739718 -0.337863E-09  0.814E-05    2.43     201.9  T
   3    -67.4739718 -0.160739E-09  0.408E-05    2.43     402.8  T

   *** convergence criteria satisfied after 3 iterations ***

         #    Occupation            Energy/Eh            Energy/eV
      -------------------------------------------------------------
         1        2.0000           -0.7637790             -20.7835
       ...           ...                  ...                  ...
        53        2.0000           -0.4268973             -11.6165
        54        2.0000           -0.4227914             -11.5047
        55        2.0000           -0.4226009             -11.4996
        56        2.0000           -0.4117742             -11.2049
        57        2.0000           -0.4111605             -11.1882
        58        2.0000           -0.4073271             -11.0839
        59        2.0000           -0.3792324             -10.3194 (HOMO)
        60                         -0.2899548              -7.8901 (LUMO)
        61                         -0.2837093              -7.7201
        62                         -0.2613235              -7.1110
        63                         -0.2534660              -6.8972
        64                         -0.2471632              -6.7257
       ...                                ...                  ...
       109                          0.7219506              19.6453
      -------------------------------------------------------------
                  HL-Gap            0.0892776 Eh            2.4294 eV
             Fermi-level           -0.3345936 Eh           -9.1048 eV

 SCC (total)                   0 d,  0 h,  0 min,  0.120 sec
 SCC setup                      ...        0 min,  0.001 sec (  0.985%)
 Dispersion                     ...        0 min,  0.001 sec (  1.030%)
 classical contributions        ...        0 min,  0.000 sec (  0.170%)
 integral evaluation            ...        0 min,  0.024 sec ( 19.576%)
 iterations                     ...        0 min,  0.027 sec ( 22.601%)
 molecular gradient             ...        0 min,  0.066 sec ( 54.958%)
 printout                       ...        0 min,  0.001 sec (  0.633%)

         :::::::::::::::::::::::::::::::::::::::::::::::::::::
         ::                     SUMMARY                     ::
         :::::::::::::::::::::::::::::::::::::::::::::::::::::
         :: total energy             -66.457313708066 Eh    ::
         :: gradient norm              0.264144987676 Eh/a0 ::
         :: HOMO-LUMO gap              2.429367309698 eV    ::
         ::.................................................::
         :: SCC energy               -67.474411998559 Eh    ::
         :: -> isotropic ES            0.113222757940 Eh    ::
         :: -> anisotropic ES          0.004611478244 Eh    ::
         :: -> anisotropic XC          0.025303044494 Eh    ::
         :: -> dispersion             -0.041348784397 Eh    ::
         :: repulsion energy           1.017098290493 Eh    ::
         :: add. restraining           0.000000000000 Eh    ::
         :: total charge               0.000000000000 e     ::
         :::::::::::::::::::::::::::::::::::::::::::::::::::::

      -----------------------------------------------------------
     |                   =====================                   |
     |                        A N C O P T                        |
     |                   =====================                   |
     |               Approximate Normal Coordinate               |
     |                Rational Function Optimizer                |
      -----------------------------------------------------------
      -----------------------------------------------------------
     |                   =====================                   |
     |                        A N C O P T                        |
     |                   =====================                   |
     |               Approximate Normal Coordinate               |
     |                Rational Function Optimizer                |
      -----------------------------------------------------------

          ...................................................
          :                      SETUP                      :
          :.................................................:
          :   optimization level            normal          :
          :   max. optcycles                   200          :
          :   ANC micro-cycles                  20          :
          :   degrees of freedom               105          :
          :.................................................:
          :   RF solver                   davidson          :
          :   write xtbopt.log                true          :
          :   linear?                        false          :
          :   energy convergence         0.5000000E-05 Eh   :
          :   grad. convergence          0.1000000E-02 Eh/α :
          :   maxmium RF displ.          1.0000000          :
          :   Hlow (freq-cutoff)         0.1000000E-01      :
          :   Hmax (freq-cutoff)         5.0000000          :
          :   S6 in model hess.         20.0000000          :
          ...................................................

generating ANC from exact Hessian ...
Using Lindh-Hessian (1995)
 Shifting diagonal of input Hessian by   9.593382787882278E-003
 Lowest  eigenvalues of input Hessian
    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
    0.010000    0.010108    0.010463    0.011387    0.011445    0.013170
    0.015123    0.015578    0.017027    0.018626    0.019773    0.022542
 Highest eigenvalues
    2.080935    2.132887    2.148451    2.190651    2.428391    2.459521


........................................................................
.............................. CYCLE    1 ..............................
........................................................................

 iter      E             dE          RMSdq      gap      omega  full diag
   1    -67.4739718 -0.674740E+02  0.214E-05    2.43       0.0  T
   2    -67.4739718 -0.312639E-11  0.156E-05    2.43    1054.6  T
   3    -67.4739718 -0.723333E-11  0.902E-06    2.43    1823.3  T
     SCC iter.                  ...        0 min,  0.023 sec
     gradient                   ...        0 min,  0.050 sec
 * total energy  :   -66.4573137 Eh     change       -0.1337241E-10 Eh
   gradient norm :     0.2641453 Eh/α   predicted     0.0000000E+00 (-100.00%)
   displ. norm   :     0.2521421 α      lambda       -0.4344089E-01
   maximum displ.:     0.1075293 α      in ANC's #54, #47, #104, ...

........................................................................
.............................. CYCLE    2 ..............................
........................................................................

 iter      E             dE          RMSdq      gap      omega  full diag
   1    -67.4895772 -0.674896E+02  0.261E-01    2.36       0.0  T
   2    -67.4910225 -0.144523E-02  0.166E-01    2.41       1.0  T
   3    -67.4912323 -0.209856E-03  0.875E-02    2.40       1.0  T
   4    -67.4912112  0.210835E-04  0.441E-02    2.41       1.0  T
   5    -67.4912435 -0.322523E-04  0.839E-03    2.40       2.0  T
   6    -67.4912459 -0.244218E-05  0.310E-03    2.40       5.3  T
   7    -67.4912460 -0.923329E-07  0.170E-03    2.40       9.7  T
   8    -67.4912461 -0.375707E-07  0.728E-04    2.40      22.6  T
   9    -67.4912461 -0.927581E-08  0.274E-04    2.40      59.9  T
     SCC iter.                  ...        0 min,  0.067 sec
     gradient                   ...        0 min,  0.051 sec
 * total energy  :   -66.4880265 Eh     change       -0.3071279E-01 Eh
   gradient norm :     0.1147647 Eh/α   predicted    -0.2310584E-01 ( -24.77%)
   displ. norm   :     0.2559392 α      lambda       -0.1616297E-01
   maximum displ.:     0.0913404 α      in ANC's #47, #25, #54, ...

........................................................................
.............................. CYCLE    3 ..............................
........................................................................

 iter      E             dE          RMSdq      gap      omega  full diag
   1    -67.5023175 -0.675023E+02  0.218E-01    2.34       0.0  T
   2    -67.5031487 -0.831264E-03  0.128E-01    2.37       1.0  T
   3    -67.5032550 -0.106258E-03  0.697E-02    2.36       1.0  T
   4    -67.5032482  0.685249E-05  0.316E-02    2.37       1.0  T
   5    -67.5032681 -0.199878E-04  0.705E-03    2.37       2.3  T
   6    -67.5032698 -0.165468E-05  0.261E-03    2.37       6.3  T
   7    -67.5032698 -0.352964E-07  0.136E-03    2.37      12.1  T
   8    -67.5032699 -0.269658E-07  0.505E-04    2.37      32.5  T
   9    -67.5032699 -0.537231E-08  0.187E-04    2.37      87.9  T
     SCC iter.                  ...        0 min,  0.034 sec
     gradient                   ...        0 min,  0.039 sec
 * total energy  :   -66.4977883 Eh     change       -0.9761826E-02 Eh
   gradient norm :     0.0327025 Eh/α   predicted    -0.8611823E-02 ( -11.78%)
   displ. norm   :     0.1935847 α      lambda       -0.2837258E-02
   maximum displ.:     0.0831211 α      in ANC's #25, #7, #35, ...

........................................................................
.............................. CYCLE    4 ..............................
........................................................................

 iter      E             dE          RMSdq      gap      omega  full diag
   1    -67.4990827 -0.674991E+02  0.116E-01    2.33       0.0  T
   2    -67.4991491 -0.663700E-04  0.694E-02    2.34       1.0  T
   3    -67.4991508 -0.170765E-05  0.371E-02    2.34       1.0  T
   4    -67.4991654 -0.146022E-04  0.855E-03    2.35       1.9  T
   5    -67.4991682 -0.276035E-05  0.340E-03    2.35       4.8  T
   6    -67.4991684 -0.224977E-06  0.162E-03    2.34      10.2  T
   7    -67.4991684 -0.285661E-08  0.697E-04    2.34      23.6  T
   8    -67.4991684 -0.120398E-07  0.199E-04    2.34      82.5  T
     SCC iter.                  ...        0 min,  0.180 sec
     gradient                   ...        0 min,  0.050 sec
 * total energy  :   -66.4996884 Eh     change       -0.1900075E-02 Eh
   gradient norm :     0.0186961 Eh/α   predicted    -0.1471820E-02 ( -22.54%)
   displ. norm   :     0.1846954 α      lambda       -0.1189654E-02
   maximum displ.:     0.0744888 α      in ANC's #25, #3, #7, ...

........................................................................
.............................. CYCLE    5 ..............................
........................................................................

 iter      E             dE          RMSdq      gap      omega  full diag
   1    -67.4988268 -0.674988E+02  0.905E-02    2.34       0.0  T
   2    -67.4988399 -0.131310E-04  0.537E-02    2.34       1.0  T
   3    -67.4988256  0.143424E-04  0.240E-02    2.34       1.0  T
   4    -67.4988449 -0.193701E-04  0.470E-03    2.34       3.5  T
   5    -67.4988456 -0.670059E-06  0.219E-03    2.34       7.5  T
   6    -67.4988456 -0.373603E-07  0.969E-04    2.34      17.0  T
   7    -67.4988456 -0.362076E-08  0.391E-04    2.34      42.1  T
     SCC iter.                  ...        0 min,  0.025 sec
     gradient                   ...        0 min,  0.044 sec
 * total energy  :   -66.5004463 Eh     change       -0.7578634E-03 Eh
   gradient norm :     0.0148084 Eh/α   predicted    -0.6151220E-03 ( -18.83%)
   displ. norm   :     0.1336047 α      lambda       -0.4674589E-03
   maximum displ.:     0.0693103 α      in ANC's #3, #7, #10, ...

........................................................................
.............................. CYCLE    6 ..............................
........................................................................

 iter      E             dE          RMSdq      gap      omega  full diag
   1    -67.5012745 -0.675013E+02  0.623E-02    2.35       0.0  T
   2    -67.5012810 -0.649049E-05  0.366E-02    2.35       1.0  T
   3    -67.5012785  0.244167E-05  0.111E-02    2.35       1.5  T
   4    -67.5012814 -0.281317E-05  0.368E-03    2.35       4.5  T
   5    -67.5012819 -0.558316E-06  0.113E-03    2.35      14.6  T
   6    -67.5012819 -0.128587E-07  0.643E-04    2.35      25.6  T
   7    -67.5012819 -0.276799E-08  0.178E-04    2.35      92.2  T

Energi linker free dan embedded hasil perhitungan xTB

In [15]:
import re

# Energi linker embedded
with open("xtb.out") as f:
    txt = f.read()

E = float(re.search(r"TOTAL ENERGY\s+(-?\d+\.\d+)", txt).group(1))

print("Single Point Energy")
print("--------------------")
print("Hartree :", E)
print("Rydberg :", E*2)
print("kcal/mol:", E*627.509)

# Energi linker free (hasil optimasi)
with open("xtb_opt.out") as f:
    txt = f.read()

Eopt = float(re.findall(r"TOTAL ENERGY\s+(-?\d+\.\d+)", txt)[-1])

print("Optimized Energy")
print("----------------")
print("Hartree :", Eopt)
print("Rydberg :", Eopt*2)
print("kcal/mol:", Eopt*627.509)

Single Point Energy
--------------------
Hartree : -66.457313707197
Rydberg : -132.914627414394
kcal/mol: -41702.56246708948
Optimized Energy
----------------
Hartree : -66.501664690907
Rydberg : -133.003329381814
kcal/mol: -41730.39310852637

Perhitungan energi konformasi banyak linker dengan xTB

Upload file linker embedded after UFF untuk kemudian dihitung nilai energi dasarnya dan energi setelah optimasi geometri dengan xTB

In [4]:
from google.colab import files
files.upload()   # upload banyak file xyz

Saving FATQID_Linker_Embed_After_UFF.xyz to FATQID_Linker_Embed_After_UFF.xyz
Saving NAWXER_Linker_Embed_After_UFF.xyz to NAWXER_Linker_Embed_After_UFF.xyz
Saving VOLPET_Linker_Embed_After_UFF.xyz to VOLPET_Linker_Embed_After_UFF.xyz

{'FATQID_Linker_Embed_After_UFF.xyz': b'37\nProperties=species:S:1:pos:R:3 pbc="F F F"\nC      8.773400    9.153000   17.322200\nC      9.516900    9.793900   16.205700\nC      9.104500   11.014600   15.701100\nH      8.233944   11.514115   16.108198\nC      9.773000   11.623700   14.652200\nH      9.386110   12.555952   14.261339\nC     11.306700    9.821400   14.595800\nH     12.190288    9.324225   14.216290\nC     10.616400    9.224800   15.667200\nH     10.992618    8.280965   16.042180\nC     10.894400   10.995900   14.082700\nC     11.709600   13.023100   12.876000\nH     11.296438   13.640089   13.662287\nC     11.597200   11.632800   12.946500\nC     12.206300   10.880300   11.937200\nH     12.162482    9.800632   11.977260\nC     12.893500   11.517500   10.888300\nC     12.918500   12.905700   10.913700\nH     13.406921   13.443164   10.112175\nC     13.596300   10.758800    9.839500\nC     13.096500    9.574700    9.419400\nH     12.164174    9.189073    9.811203\nC     13.730600    8.825000    8.393200\nH     13.291064    7.887589    8.075559\nC     14.917600    9.306000    7.840600\nC     15.386100   10.493000    8.283200\nH     16.264543   10.963278    7.867334\nC     14.739500   11.202100    9.284100\nH     15.190853   12.129248    9.614437\nC     15.629700    8.525100    6.822800\nO     16.727700    8.990500    6.417900\nO     15.098100    7.457200    6.424900\nN     12.357100   13.644100   11.888100\nO      7.738900    9.704600   17.749300\nO      9.242900    8.062500   17.735800\nH      8.793255    7.550080   18.485613\nH     17.418551    9.430086    7.013418\n',
 'NAWXER_Linker_Embed_After_UFF.xyz': b'62\nProperties=species:S:1:pos:R:3 pbc="F F F"\nC     13.721600   11.331000    6.859100\nC     12.836800   12.484500    7.252800\nC     12.349400   12.577200    8.545200\nH     12.498987   11.806671    9.286058\nC     11.574800   13.658700    8.927400\nH     11.221940   13.714682    9.949821\nC     11.294000   14.674000    8.033900\nC     12.534500   13.485100    6.348800\nH     12.901762   13.448764    5.330808\nC     11.783600   14.582300    6.745600\nH     11.580763   15.364911    6.024058\nC     10.551900   15.892300    8.453600\nN     11.107000   17.049100    8.056800\nO     14.055300   10.531300    7.755400\nO     14.068700   11.271000    5.651200\nC      6.209200   11.331000   10.810400\nC      7.094000   12.484500   10.416700\nC      7.581400   12.577200    9.124300\nH      7.358524   11.858002    8.352929\nC      8.356000   13.658700    8.742100\nH      8.693720   13.724546    7.715038\nC      8.636800   14.674000    9.635600\nC      7.396300   13.485100   11.320700\nH      7.029056   13.448760   12.338696\nC      8.147200   14.582300   10.923900\nH      8.350034   15.364920   11.645439\nC      9.378900   15.892300    9.215900\nN      8.823800   17.049100    9.612700\nO      5.875500   10.531300    9.914100\nO      5.862100   11.271000   12.018300\nC     13.721600   22.767300    6.859100\nC     12.836800   21.613800    7.252800\nC     12.349400   21.521100    8.545200\nH     12.580519   22.299832    9.259770\nC     11.574800   20.439600    8.927400\nH     11.231798   20.379518    9.952722\nC     11.294000   19.424300    8.033900\nC     12.534500   20.613200    6.348800\nH     12.907600   20.676971    5.335303\nC     11.783600   19.516000    6.745600\nH     11.579851   18.734379    6.023336\nC     10.551900   18.206000    8.453600\nO     14.055300   23.567000    7.755400\nO     14.068700   22.827300    5.651200\nC      6.209200   22.767300   10.810400\nC      7.094000   21.613800   10.416700\nC      7.581400   21.521100    9.124300\nH      7.358427   22.240254    8.352913\nC      8.356000   20.439600    8.742100\nH      8.693579   20.373668    7.715001\nC      8.636800   19.424300    9.635600\nC      7.396300   20.613200   11.320700\nH      7.029047   20.649535   12.338695\nC      8.147200   19.516000   10.923900\nH      8.350021   18.733372   11.645433\nC      9.378900   18.206000    9.215900\nO      5.875500   23.567000    9.914100\nO      5.862100   22.827300   12.018300\nH      6.501208   10.167496    9.208113\nH     14.242561   10.787277    8.716118\nH      6.501222   23.930832    9.208144\nH     14.672770   23.569386    5.317262\n',
 'VOLPET_Linker_Embed_After_UFF.xyz': b'15\nProperties=species:S:1:pos:R:3 pbc="F F F"\nS     17.159900   16.548700   11.038500\nO     19.656900   19.059700    9.443300\nO     19.278600   18.422500   11.554300\nO     15.068400   14.610800   11.459300\nO     14.329500   14.486200    9.385000\nC     17.567900   17.180300    8.653600\nH     17.968036   17.632641    7.755582\nC     16.515700   16.258400    8.650300\nH     16.026112   15.933067    7.741394\nC     19.092300   18.363700   10.331400\nC     16.164000   15.838000    9.863200\nC     18.016000   17.442400    9.888200\nC     15.111600   14.906300   10.236400\nH     14.365368   13.977128   11.822086\nH     18.989437   17.760477   12.262014\n'}

Perhitungan energi konformasi linker

In [5]:
import glob
import subprocess
import re
import pandas as pd

results = []

for xyz in glob.glob("*.xyz"):
    name = xyz.replace(".xyz","")

    print(f"Processing {xyz} ...")

    # single point
    sp_cmd = f"xtb {xyz} --gfn2 | tee {name}_sp.out"
    subprocess.run(sp_cmd, shell=True)

    # optimization
    opt_cmd = f"xtb {xyz} --opt --gfn2 | tee {name}_opt.out"
    subprocess.run(opt_cmd, shell=True)

    # parse energies
    Esp = float(re.search(
        r"TOTAL ENERGY\s+(-?\d+\.\d+)",
        open(f"{name}_sp.out").read()
    ).group(1))

    Eopt = float(re.findall(
        r"TOTAL ENERGY\s+(-?\d+\.\d+)",
        open(f"{name}_opt.out").read()
    )[-1])

    dE = Esp - Eopt

    results.append([name, Esp, Eopt, dE])

# Hasil
df = pd.DataFrame(results, columns=[
    "Molecule",
    "Single Point (Eh)",
    "Optimized (Eh)",
    "Conformation ΔE (Eh)"
])

df["Single (kcal/mol)"] = df["Single Point (Eh)"] * 627.509
df["Optimized (kcal/mol)"] = df["Optimized (Eh)"] * 627.509
df["ΔE (kcal/mol)"] = df["Conformation ΔE (Eh)"] * 627.509

df["Single (Ry)"] = df["Single Point (Eh)"] * 2
df["Optimized (Ry)"] = df["Optimized (Eh)"] * 2
df["ΔE (Ry)"] = df["Conformation ΔE (Eh)"] * 2

df

Processing FATQID_Linker_Embed_After_UFF.xyz ...
Processing NAWXER_Linker_Embed_After_UFF.xyz ...
Processing VOLPET_Linker_Embed_After_UFF.xyz ...

,Molecule,Single Point (Eh),Optimized (Eh),Conformation ΔE (Eh),Single (kcal/mol),Optimized (kcal/mol),ΔE (kcal/mol),Single (Ry),Optimized (Ry),ΔE (Ry)
0,FATQID_Linker_Embed_After_UFF,-66.457314,-66.501665,0.044351,-41702.562467,-41730.393109,27.830641,-132.914627,-133.003329,0.088702
1,NAWXER_Linker_Embed_After_UFF,-117.030478,-117.110537,0.080059,-73437.678158,-73487.916127,50.237969,-234.060956,-234.221075,0.160119
2,VOLPET_Linker_Embed_After_UFF,-34.360648,-34.394272,0.033624,-21561.616010,-21582.715468,21.099458,-68.721296,-68.788545,0.067248

Perhitungan RMSD, delta length dan angle pada struktur embedded dan free

In [16]:
# Fungsi RMSD dengan Kabsch alignment
def kabsch_rmsd(P, Q):
    """
    P, Q: numpy array (N,3)
    Returns RMSD after optimal alignment of P onto Q
    """
    # Center the structures
    P_centered = P - P.mean(axis=0)
    Q_centered = Q - Q.mean(axis=0)

    # Covariance matrix
    C = np.dot(P_centered.T, Q_centered)

    # SVD
    V, S, Wt = np.linalg.svd(C)
    d = np.sign(np.linalg.det(np.dot(Wt.T, V.T)))
    D = np.diag([1,1,d])
    U = np.dot(Wt.T, np.dot(D, V.T))

    # Rotate P
    P_rot = np.dot(P_centered, U)

    # RMSD
    rmsd = np.sqrt(np.mean(np.sum((P_rot - Q_centered)**2, axis=1)))
    return rmsd, P_rot

# Jari-jari kovalen (Å)
cov_radii = {
    'H': 0.31, 'C': 0.76, 'N': 0.71, 'O': 0.66, 'F': 0.57,
    'P': 1.07, 'S': 1.05, 'Cl': 1.02, 'Br': 1.20, 'I': 1.39
}

# Deteksi ikatan otomatis
def detect_bonds(symbols, coords, scale=1.2):
    bonds = []
    N = len(symbols)
    for i,j in combinations(range(N),2):
        if symbols[i] not in cov_radii or symbols[j] not in cov_radii:
            continue
        cutoff = scale*(cov_radii[symbols[i]] + cov_radii[symbols[j]])
        dist = np.linalg.norm(coords[i]-coords[j])
        if dist <= cutoff:
            bonds.append((i,j))
    return bonds

# Hitung panjang ikatan & sudut
def bond_lengths(coords, bonds):
    return np.array([np.linalg.norm(coords[i]-coords[j]) for i,j in bonds])

def bond_angles(coords, bonds):
    angles = []
    triplets = []
    neighbor_dict = {}
    for i,j in bonds:
        neighbor_dict.setdefault(i, []).append(j)
        neighbor_dict.setdefault(j, []).append(i)
    for center, neighbors in neighbor_dict.items():
        for i in range(len(neighbors)):
            for j in range(i+1, len(neighbors)):
                a,b = neighbors[i], neighbors[j]
                v1 = coords[a]-coords[center]
                v2 = coords[b]-coords[center]
                cos_theta = np.dot(v1,v2)/(np.linalg.norm(v1)*np.linalg.norm(v2))
                cos_theta = np.clip(cos_theta, -1.0, 1.0)
                theta = np.arccos(cos_theta)*180/np.pi
                angles.append(theta)
                triplets.append((a,center,b))
    return np.array(angles), triplets

# Fungsi utama evaluasi distorsi
def evaluate_distortion(file_free, file_embedded, scale=1.2):
    atoms_free = read(file_free)
    atoms_emb = read(file_embedded)

    symbols_free = atoms_free.get_chemical_symbols()
    symbols_emb = atoms_emb.get_chemical_symbols()

    coords_free = atoms_free.get_positions()
    coords_emb = atoms_emb.get_positions()
    coords_emb_ordered = coords_emb

    # RMSD
    rmsd, coords_free_aligned = kabsch_rmsd(coords_free, coords_emb_ordered)

    # Deteksi ikatan
    bonds_free = detect_bonds(symbols_free, coords_free, scale=1.5)
    lengths_free = bond_lengths(coords_free, bonds_free)
    lengths_emb = bond_lengths(coords_emb_ordered, bonds_free)

    angles_free, triplets = bond_angles(coords_free, bonds_free)
    angles_emb, _ = bond_angles(coords_emb_ordered, bonds_free)
    delta_lengths = lengths_emb - lengths_free
    delta_angles = angles_emb - angles_free

    df_bonds = pd.DataFrame({
        'atom_i':[i for i,j in bonds_free],
        'atom_j':[j for i,j in bonds_free],
        'length_free':lengths_free,
        'length_embedded':lengths_emb,
        'delta_length':delta_lengths
    })

    df_angles = pd.DataFrame({
        'atom_i':[a for a,c,b in triplets],
        'atom_center':[c for a,c,b in triplets],
        'atom_k':[b for a,c,b in triplets],
        'angle_free':angles_free,
        'angle_embedded':angles_emb,
        'delta_angle':delta_angles
    })

    return rmsd, df_bonds, df_angles, symbols_free, coords_free_aligned, coords_emb_ordered

# Upload CIF
print("Upload CIF file linker free:")
uploaded_free = files.upload()
file_free = list(uploaded_free.keys())[0]

print("Upload CIF file linker embedded:")
uploaded_emb = files.upload()
file_embedded = list(uploaded_emb.keys())[0]

# Evaluasi distorsi
rmsd, df_bonds, df_angles, symbols_free, coords_free_aligned, coords_emb_ordered = evaluate_distortion(file_free, file_embedded)

print(f"\nRMSD (Å): {rmsd:.4f}")
print("\nΔBond Lengths:")
display(df_bonds)
print("\nΔBond Angles:")
display(df_angles)

# Statistik Distorsi
ME_delta_length = df_bonds['delta_length'].mean()
ME_delta_angle  = df_angles['delta_angle'].mean()

print("\n===== Mean Error (ME) =====")
print(f"ME ΔBond Length (Å): {ME_delta_length:.6f}")
print(f"ME ΔBond Angle (deg): {ME_delta_angle:.4f}")

print("\nInterpretation:")
if ME_delta_length > 0:
    print("→ Secara rata-rata terjadi pemanjangan ikatan")
else:
    print("→ Secara rata-rata terjadi pemendekan ikatan")

if ME_delta_angle > 0:
    print("→ Sudut ikatan cenderung melebar")
else:
    print("→ Sudut ikatan cenderung menyempit")

Upload CIF file linker free:

Saving FATQID_Linker_Free Hasil Opt.xyz to FATQID_Linker_Free Hasil Opt.xyz
Upload CIF file linker embedded:

Saving FATQID_Linker_Embed_After_UFF.xyz to FATQID_Linker_Embed_After_UFF (1).xyz

RMSD (Å): 0.0810

ΔBond Lengths:

    atom_i  atom_j  length_free  length_embedded  delta_length
0        0       1     1.482244         1.486646      0.004402
1        0      33     1.220769         1.247745      0.026976
2        0      34     1.369356         1.257253     -0.112103
3        1       2     1.400580         1.383764     -0.016816
4        1       8     1.400696         1.350095     -0.050600
5        2       3     1.090285         1.083103     -0.007182
6        2       4     1.387361         1.384950     -0.002411
7        4       5     1.090880         1.082382     -0.008498
8        4      10     1.406416         1.405703     -0.000713
9        6       7     1.090926         1.082561     -0.008365
10       6       8     1.388648         1.407247      0.018598
11       6      10     1.404939         1.346370     -0.058569
12       8       9     1.088666         1.083039     -0.005627
13      10      13     1.475082         1.480041      0.004959
14      11      12     1.093677         1.081492     -0.012185
15      11      13     1.405155         1.396617     -0.008538
16      11      32     1.335744         1.334483     -0.001262
17      13      14     1.398718         1.398551     -0.000166
18      14      15     1.091167         1.081299     -0.009868
19      14      16     1.398286         1.406577      0.008291
20      16      17     1.405517         1.388657     -0.016860
21      16      19     1.475248         1.472934     -0.002314
22      17      18     1.093596         1.081603     -0.011993
23      17      32     1.336066         1.345310      0.009245
24      19      20     1.406226         1.352175     -0.054051
25      19      27     1.404337         1.346065     -0.058273
26      20      21     1.091181         1.082335     -0.008845
27      20      22     1.386924         1.420288      0.033364
28      22      23     1.090158         1.082971     -0.007187
29      22      24     1.400943         1.394882     -0.006061
30      24      25     1.401445         1.350687     -0.050758
31      24      29     1.495330         1.467245     -0.028085
32      25      26     1.093328         1.079707     -0.013621
33      25      27     1.389866         1.386620     -0.003246
34      27      28     1.090746         1.082795     -0.007951
35      29      30     1.369393         1.259423     -0.109971
36      29      31     1.214782         1.257511      0.042728
37      30      36     0.978428         1.012498      0.034070
38      34      35     0.981357         1.013397      0.032041

ΔBond Angles:

    atom_i  atom_center  atom_k  angle_free  angle_embedded  delta_angle
0        1            0      33  125.104174      118.759682    -6.344493
1        1            0      34  112.723650      115.736216     3.012567
2       33            0      34  122.170975      125.482155     3.311179
3        0            1       2  118.421028      120.339203     1.918176
4        0            1       8  122.312437      121.676372    -0.636065
5        2            1       8  119.263409      117.976867    -1.286542
6        0           34      35  106.000625      121.083968    15.083343
7        1            2       3  118.721696      120.618799     1.897103
8        1            2       4  120.364727      121.351958     0.987230
9        3            2       4  120.911086      118.021181    -2.889905
10       1            8       6  120.222152      121.631121     1.408969
11       1            8       9  119.481839      120.806800     1.324961
12       6            8       9  120.293803      117.558901    -2.734902
13       2            4       5  119.441397      118.669350    -0.772047
14       2            4      10  120.874777      119.701305    -1.173472
15       5            4      10  119.662404      121.568288     1.905884
16       4           10       6  118.281003      118.652532     0.371529
17       4           10      13  120.839262      119.844026    -0.995237
18       6           10      13  120.878879      121.502866     0.623988
19       7            6       8  119.271813      118.201488    -1.070325
20       7            6      10  119.721162      121.129703     1.408541
21       8            6      10  120.989616      120.647902    -0.341715
22      10           13      11  121.237210      120.354446    -0.882764
23      10           13      14  121.871815      121.957199     0.085384
24      11           13      14  116.870934      117.654760     0.783826
25      12           11      13  120.125131      120.031197    -0.093934
26      12           11      32  116.093562      117.264586     1.171024
27      13           11      32  123.760502      122.660687    -1.099815
28      11           32      17  118.084431      118.897678     0.813247
29      13           14      15  119.486686      119.528710     0.042024
30      13           14      16  120.622682      120.477052    -0.145630
31      15           14      16  119.889022      119.983901     0.094879
32      14           16      17  116.827891      116.616796    -0.211095
33      14           16      19  121.999755      122.056192     0.056436
34      17           16      19  121.172264      121.289248     0.116984
35      16           17      18  120.208708      119.427750    -0.780958
36      16           17      32  123.784951      123.671069    -0.113882
37      18           17      32  115.992305      116.900359     0.908054
38      16           19      20  121.460638      119.730827    -1.729811
39      16           19      27  120.553603      121.964586     1.410983
40      20           19      27  117.985616      118.302300     0.316684
41      19           20      21  119.840440      121.193828     1.353387
42      19           20      22  121.009226      121.445991     0.436765
43      21           20      22  119.134634      117.262363    -1.872270
44      19           27      25  120.927553      121.698789     0.771236
45      19           27      28  119.866006      120.672556     0.806550
46      25           27      28  119.192129      117.626942    -1.565187
47      20           22      23  121.187719      119.184553    -2.003166
48      20           22      24  120.838681      118.956218    -1.882464
49      23           22      24  117.971672      121.847619     3.875946
50      22           24      25  118.408216      117.930034    -0.478182
51      22           24      29  117.374527      120.283873     2.909346
52      25           24      29  124.216528      121.782056    -2.434472
53      24           25      26  121.551150      122.599697     1.048546
54      24           25      27  120.814186      121.614367     0.800181
55      26           25      27  117.620900      115.764461    -1.856439
56      24           29      30  117.074277      116.709506    -0.364771
57      24           29      31  123.476128      117.794185    -5.681943
58      30           29      31  119.448135      125.495856     6.047720
59      29           30      36  110.446630      124.486488    14.039858

===== Mean Error (ME) =====
ME ΔBond Length (Å): -0.011986
ME ΔBond Angle (deg): 0.4950

Interpretation:
→ Secara rata-rata terjadi pemendekan ikatan
→ Sudut ikatan cenderung melebar

Visualiasi distori setelah free linker digeser agar tidak overlapping tapi perhitungan tetap di 1 pusat yang sama

In [17]:
# Safety check
assert len(symbols_free) == coords_free_aligned.shape[0] == coords_emb_ordered.shape[0], \
    "ERROR: Jumlah atom tidak konsisten!"

# Centering
coords_free_centered = coords_free_aligned - coords_free_aligned.mean(axis=0)
coords_emb_centered  = coords_emb_ordered  - coords_emb_ordered.mean(axis=0)

# Atom-wise displacement (Δr_i)
delta_r = np.linalg.norm(coords_emb_centered - coords_free_centered, axis=1)

df_atoms = pd.DataFrame({
    'atom_index': np.arange(len(symbols_free)),
    'element': symbols_free,
    'delta_r (Å)': delta_r
})

print("\nAtom Δr minimum:")
display(df_atoms.loc[df_atoms['delta_r (Å)'].idxmin()])

print("\nAtom Δr maksimum:")
display(df_atoms.loc[df_atoms['delta_r (Å)'].idxmax()])

print("\nAtom-wise displacement (Δr_i):")
display(df_atoms)

print(f"\nΔr min = {delta_r.min():.3f} Å")
print(f"Δr max = {delta_r.max():.3f} Å")

# Normalisasi warna
delta_min = delta_r.min()
delta_max = delta_r.max()

norm = mcolors.Normalize(vmin=delta_min, vmax=delta_max)
cmap = cm.get_cmap('viridis')

def displacement_to_color(val, vmin, vmax):
    t = norm(val)
    r, g, b, _ = cmap(t)
    return f"rgb({int(255*r)},{int(255*g)},{int(255*b)})"

colors = [displacement_to_color(v, delta_min, delta_max) for v in delta_r]
assert None not in colors, "Ada atom tanpa warna!"

# Visual offset (hanya untuk visualisasi)
VISUAL_SHIFT = np.array([0.0, 4.9, 0.0])  # geser embedded ke (+y)
coords_emb_visual = coords_emb_centered + VISUAL_SHIFT

# py3Dmol visualization: Overlay + RMSD mapping
view = py3Dmol.view(width=900, height=650)

# Free linker (aligned + centered)
xyz_free = f"{len(symbols_free)}\nfree_aligned_centered\n"
for s, c in zip(symbols_free, coords_free_centered):
    xyz_free += f"{s} {c[0]:.6f} {c[1]:.6f} {c[2]:.6f}\n"

view.addModel(xyz_free, "xyz")
view.setStyle(
    {'model': 0},
    {
        'stick': {'radius': 0.13, 'color': 'lightgray'},
        'sphere': {'scale': 0.18, 'color': 'lightgray'}
    }
)

# Embedded linker
xyz_emb = f"{len(symbols_free)}\nembedded_centered_visual\n"
for s, c in zip(symbols_free, coords_emb_visual):
    xyz_emb += f"{s} {c[0]:.6f} {c[1]:.6f} {c[2]:.6f}\n"

view.addModel(xyz_emb, "xyz")
view.setStyle({'model': 1}, {})

for i, color in enumerate(colors):
    view.setStyle(
        {'model': 1, 'index': i},
        {
            'sphere': {'scale': 0.32, 'color': color},
            'stick':  {'radius': 0.18, 'color': color}
        }
    )

# View settings
view.zoomTo()
view.setBackgroundColor('white')

view.setViewStyle({
    'style': 'outline',
    'color': 'black',
    'width': 0.02
})

# Axis legend (ON/OFF)
SHOW_AXIS = True

if SHOW_AXIS:
    axis_len = 2.5

    label_style = {
        'backgroundColor': 'rgba(255,255,255,0.85)',
        'fontSize': 18,
        'padding': 4,
        'borderRadius': 4,
        'fontColor': 'black'
    }

    # X-axis
    view.addArrow({
        'start': {'x': 0, 'y': 0, 'z': 0},
        'end':   {'x': axis_len, 'y': 0, 'z': 0},
        'radius': 0.08,
        'color': 'red'
    })
    #view.addLabel("X", {
        #**label_style,
        #'position': {'x': axis_len + 0.3, 'y': 0, 'z': 0},
        #'fontColor': 'red'
    #})

    # Y-axis
    view.addArrow({
        'start': {'x': 0, 'y': 0, 'z': 0},
        'end':   {'x': 0, 'y': axis_len, 'z': 0},
        'radius': 0.08,
        'color': 'green'
    })
    #view.addLabel("Y", {
        #**label_style,
        #'position': {'x': 0, 'y': axis_len + 0.3, 'z': 0},
        #'fontColor': 'green'
    #})

    # Z-axis
    view.addArrow({
        'start': {'x': 0, 'y': 0, 'z': 0},
        'end':   {'x': 0, 'y': 0, 'z': axis_len},
        'radius': 0.08,
        'color': 'blue'
    })
    #view.addLabel("Z", {
        #**label_style,
        #'position': {'x': 0, 'y': 0, 'z': axis_len + 0.3},
        #'fontColor': 'blue'
    #})

view.show()

# Fixed color legend (toggleable)
levels = np.linspace(delta_min, delta_max, 5)
legend_colors = [displacement_to_color(v, delta_min, delta_max) for v in levels]

legend_items = ""
for v, col in zip(levels, legend_colors):
    legend_items += f"""
    <div style="display:flex; align-items:center; margin-bottom:4px;">
        <div style="
            width:18px;
            height:18px;
            background:{col};
            margin-right:8px;
            border-radius:3px;
        "></div>
        <span style="font-size:13px;">Δr = {v:.2f} Å</span>
    </div>
    """

display(HTML(f"""
<div id="legend-box" style="
    position: fixed;
    bottom: 20px;
    left: 20px;
    background: rgba(255,255,255,0.9);
    padding: 10px 12px;
    border-radius: 8px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.15);
    font-family: Arial, sans-serif;
    z-index: 9999;
">
    <b style="font-size:14px;">Atom-wise Δr</b>
    <div style="margin-top:8px;">
        {legend_items}
    </div>
</div>
"""))

display(HTML("""
<button onclick="
    const el = document.getElementById('legend-box');
    el.style.display = (el.style.display === 'none') ? 'block' : 'none';
" style="
    position: fixed;
    bottom: 20px;
    left: 200px;
    z-index: 10001;
    padding: 6px 10px;
    font-size: 13px;
    background: white;
    border: 1px solid #aaa;
    border-radius: 6px;
    cursor: pointer;
">
Legend
</button>
"""))

Atom Δr minimum:

atom_index           15
element               H
delta_r (Å)    0.012597
Name: 15, dtype: object

Atom Δr maksimum:

atom_index           30
element               O
delta_r (Å)    0.249346
Name: 30, dtype: object

Atom-wise displacement (Δr_i):

    atom_index element  delta_r (Å)
0            0       C     0.033222
1            1       C     0.013592
2            2       C     0.028752
3            3       H     0.063316
4            4       C     0.023630
5            5       H     0.015522
6            6       C     0.040895
7            7       H     0.030345
8            8       C     0.054826
9            9       H     0.055024
10          10       C     0.019564
11          11       C     0.025029
12          12       H     0.043827
13          13       C     0.020685
14          14       C     0.024607
15          15       H     0.012597
16          16       C     0.030614
17          17       C     0.032052
18          18       H     0.049058
19          19       C     0.018253
20          20       C     0.047287
21          21       H     0.047607
22          22       C     0.026385
23          23       H     0.078084
24          24       C     0.028482
25          25       C     0.065344
26          26       H     0.076769
27          27       C     0.062529
28          28       H     0.068910
29          29       C     0.080114
30          30       O     0.249346
31          31       O     0.139372
32          32       N     0.036408
33          33       O     0.099488
34          34       O     0.088715
35          35       H     0.146533
36          36       H     0.242964

Δr min = 0.013 Å
Δr max = 0.249 Å

/tmp/ipython-input-2038251782.py:35: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = cm.get_cmap('viridis')

Visualisasi distori overlapping di 1 pusat

In [18]:
# Safety check
assert len(symbols_free) == coords_free_aligned.shape[0] == coords_emb_ordered.shape[0], \
    "ERROR: Jumlah atom tidak konsisten!"

# Centering
coords_free_centered = coords_free_aligned - coords_free_aligned.mean(axis=0)
coords_emb_centered  = coords_emb_ordered  - coords_emb_ordered.mean(axis=0)

# Atom-wise displacement (Δr_i)
delta_r = np.linalg.norm(coords_emb_centered - coords_free_centered, axis=1)

df_atoms = pd.DataFrame({
    'atom_index': np.arange(len(symbols_free)),
    'element': symbols_free,
    'delta_r (Å)': delta_r
})

print("\nAtom Δr minimum:")
display(df_atoms.loc[df_atoms['delta_r (Å)'].idxmin()])

print("\nAtom Δr maksimum:")
display(df_atoms.loc[df_atoms['delta_r (Å)'].idxmax()])

print("\nAtom-wise displacement (Δr_i):")
display(df_atoms)

print(f"\nΔr min = {delta_r.min():.3f} Å")
print(f"Δr max = {delta_r.max():.3f} Å")

# Normalisasi warna
delta_min = delta_r.min()
delta_max = delta_r.max()

norm = mcolors.Normalize(vmin=delta_min, vmax=delta_max)
cmap = cm.get_cmap('viridis')

def displacement_to_color(val, vmin, vmax):
    t = norm(val)
    r, g, b, _ = cmap(t)
    return f"rgb({int(255*r)},{int(255*g)},{int(255*b)})"

colors = [displacement_to_color(v, delta_min, delta_max) for v in delta_r]
assert None not in colors, "Ada atom tanpa warna!"

# py3Dmol visualization: Overlay + RMSD mapping
view = py3Dmol.view(width=900, height=650)

# Free linker (aligned + centered)
xyz_free = f"{len(symbols_free)}\nfree_aligned_centered\n"
for s, c in zip(symbols_free, coords_free_centered):
    xyz_free += f"{s} {c[0]:.6f} {c[1]:.6f} {c[2]:.6f}\n"

view.addModel(xyz_free, "xyz")
view.setStyle(
    {'model': 0},
    {
        'stick': {'radius': 0.13, 'color': 'lightgray'},
        'sphere': {'scale': 0.18, 'color': 'lightgray'}
    }
)

# Embedded linker
xyz_emb = f"{len(symbols_free)}\nembedded_centered\n"
for s, c in zip(symbols_free, coords_emb_centered):
    xyz_emb += f"{s} {c[0]:.6f} {c[1]:.6f} {c[2]:.6f}\n"

view.addModel(xyz_emb, "xyz")

view.setStyle({'model': 1}, {})

for i, color in enumerate(colors):
    view.setStyle(
        {'model': 1, 'index': i},
        {
            'sphere': {'scale': 0.32, 'color': color},
            'stick':  {'radius': 0.18, 'color': color}
        }
    )

# View settings
view.zoomTo()
view.setBackgroundColor('white')

view.setViewStyle({
    'style': 'outline',
    'color': 'black',
    'width': 0.02
})

# Legend axis
SHOW_AXIS = False
if SHOW_AXIS:
    axis_len = 2.5

    label_style = {
        'backgroundColor': 'rgba(255,255,255,0.85)',
        'fontSize': 18,
        'padding': 4,
        'borderRadius': 4,
        'fontColor': 'black'
    }

    # X-axis
    view.addArrow({
        'start': {'x': 0, 'y': 0, 'z': 0},
        'end':   {'x': axis_len, 'y': 0, 'z': 0},
        'radius': 0.08,
        'color': 'red'
    })
    view.addLabel("X", {
        **label_style,
        'position': {'x': axis_len + 0.3, 'y': 0, 'z': 0},
        'fontColor': 'red'
    })

    # Y-axis
    view.addArrow({
        'start': {'x': 0, 'y': 0, 'z': 0},
        'end':   {'x': 0, 'y': axis_len, 'z': 0},
        'radius': 0.08,
        'color': 'green'
    })
    view.addLabel("Y", {
        **label_style,
        'position': {'x': 0, 'y': axis_len + 0.3, 'z': 0},
        'fontColor': 'green'
    })

    # Z-axis
    view.addArrow({
        'start': {'x': 0, 'y': 0, 'z': 0},
        'end':   {'x': 0, 'y': 0, 'z': axis_len},
        'radius': 0.08,
        'color': 'blue'
    })
    view.addLabel("Z", {
        **label_style,
        'position': {'x': 0, 'y': 0, 'z': axis_len + 0.3},
        'fontColor': 'blue'
    })


view.show()

# Legend
levels = np.linspace(delta_min, delta_max, 5)
legend_colors = [displacement_to_color(v, delta_min, delta_max) for v in levels]

legend_items = ""
for v, col in zip(levels, legend_colors):
    legend_items += f"""
    <div style="display:flex; align-items:center; margin-bottom:4px;">
        <div style="
            width:18px;
            height:18px;
            background:{col};
            margin-right:8px;
            border-radius:3px;
        "></div>
        <span style="font-size:13px;">Δr = {v:.2f} Å</span>
    </div>
    """

display(HTML(f"""
<div id="legend-box" style="
    position: fixed;
    bottom: 20px;
    left: 20px;
    background: rgba(255,255,255,0.9);
    padding: 10px 12px;
    border-radius: 8px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.15);
    font-family: Arial, sans-serif;
    z-index: 9999;
">
    <b style="font-size:14px;">Atom-wise Δr</b>
    <div style="margin-top:8px;">
        {legend_items}
    </div>
</div>
"""))

display(HTML("""
<button onclick="
    const el = document.getElementById('legend-box');
    el.style.display = (el.style.display === 'none') ? 'block' : 'none';
" style="
    position: fixed;
    bottom: 20px;
    left: 200px;
    z-index: 10001;
    padding: 6px 10px;
    font-size: 13px;
    background: white;
    border: 1px solid #aaa;
    border-radius: 6px;
    cursor: pointer;
">
Legend
</button>
"""))

Atom Δr minimum:

atom_index           15
element               H
delta_r (Å)    0.012597
Name: 15, dtype: object

Atom Δr maksimum:

atom_index           30
element               O
delta_r (Å)    0.249346
Name: 30, dtype: object

Atom-wise displacement (Δr_i):

    atom_index element  delta_r (Å)
0            0       C     0.033222
1            1       C     0.013592
2            2       C     0.028752
3            3       H     0.063316
4            4       C     0.023630
5            5       H     0.015522
6            6       C     0.040895
7            7       H     0.030345
8            8       C     0.054826
9            9       H     0.055024
10          10       C     0.019564
11          11       C     0.025029
12          12       H     0.043827
13          13       C     0.020685
14          14       C     0.024607
15          15       H     0.012597
16          16       C     0.030614
17          17       C     0.032052
18          18       H     0.049058
19          19       C     0.018253
20          20       C     0.047287
21          21       H     0.047607
22          22       C     0.026385
23          23       H     0.078084
24          24       C     0.028482
25          25       C     0.065344
26          26       H     0.076769
27          27       C     0.062529
28          28       H     0.068910
29          29       C     0.080114
30          30       O     0.249346
31          31       O     0.139372
32          32       N     0.036408
33          33       O     0.099488
34          34       O     0.088715
35          35       H     0.146533
36          36       H     0.242964

Δr min = 0.013 Å
Δr max = 0.249 Å

/tmp/ipython-input-2315424417.py:35: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = cm.get_cmap('viridis')